%% sepia_universal_variables
%
% Description: a script contains all the method names and related function
% names
%
% Kwok-shing Chan @ DCCN
% k.chan@donders.ru.nl
% Date created: 6 March 2020
% Date modified: 
%
% DO NOT change the variable name
% DO NOT change the order of the entities, add a new one at the end instead
%
%% General parameterss
gyro = 42.57747892; % Larmor frequency of 1H, in MHz/T

%% Total field recovery related parameters
% phase unwrapping method available in SEPIA
methodUnwrapName        = {'Laplacian (MEDI)',...
                           'Laplacian (STI suite)',...
                           '3D best path',...
                           'Region growing (MEDI)',...
                           'Graphcut',...
                           'SEGUE'};
                       
% Echo combination method available in SEPIA
methodEchoCombineName   = {'Optimum weights',...
                           'MEDI nonlinear fit',...
                           'MEDI nonlinear fit (Bipolar, testing)'};

% Methods to exclude unreliable voxels                       
methodExcludedName      = {'Weighting map',...
                           'Brain mask'};

% Wrapper to access phase unwrapping algorithms
wrapper_Unwrap_function	= {'Wrapper_Unwrap_LaplacianMEDI',...
                           'Wrapper_Unwrap_LaplacianSTI',...
                           'Wrapper_Unwrap_3DBestPath',...
                           'Wrapper_Unwrap_RegionGrowing',...
                           'Wrapper_Unwrap_Graphcut',...
                           'Wrapper_Unwrap_SEGUE',...
                           } ;

%% background field removal related parameters
% Background field removal method available in SEPIA
methodBFRName           = {'LBV',...
                           'PDF',...
                           'RESHARP',...
                           'SHARP',...
                           'VSHARP (STI suite)',...
                           'VSHARP',...
                           'iHARPERELLA'};

% functions that generate and read BFR algorithm parameters
config_BFR_function     = {'get_set_bfr_lbv',...
                           'get_set_bfr_pdf',...
                           'get_set_bfr_resharp',...
                           'get_set_bfr_sharp',...
                           'get_set_bfr_vsharpsti',...
                           'get_set_bfr_vsharp',...
                           'get_set_bfr_iharperella',...
                           };

% Wrapper to access BFR algorithms
wrapper_BFR_function    = {'Wrapper_BFR_LBV',...
                           'Wrapper_BFR_PDF',...
                           'Wrapper_BFR_RESHARP',...
                           'Wrapper_BFR_SHARP',...
                           'Wrapper_BFR_VSHARPSTI',...
                           'Wrapper_BFR_VSHARP',...
                           'Wrapper_BFR_iHARPERELLA',...
                           } ;

%% QSM related parameters
% QSM methods available in SEPIA
methodQSMName           = {'TKD',...
                           'Closed-form solution',...
                           'NDI',...
                           'STI suite iLSQR',...
                           'iLSQR',...
                           'FANSI',...
                           'Star-QSM',...
                           'MEDI'};

% Referencing region available in SEPIA
tissueName              = {'None',...
                           'Brain mask',...
                           'CSF'};

% functions that generate and read QSM algorithm parameters                       
config_QSM_function     = {'get_set_qsm_tkd',...
                           'get_set_qsm_cfs',...
                           'get_set_qsm_ndi',...
                           'get_set_qsm_stisuiteilsqr',...
                           'get_set_qsm_ilsqr',...
                           'get_set_qsm_fansi',...
                           'get_set_qsm_starqsm',...
                           'get_set_qsm_medi',...
                           };

% Wrapper to access QSM algorithms
wrapper_QSM_function    = {'Wrapper_QSM_TKD',...
                           'Wrapper_QSM_CFSL2',...
                           'Wrapper_QSM_NDI',...
                           'Wrapper_QSM_STISuiteiLSQRv3',...
                           'Wrapper_QSM_iLSQR',...
                           'Wrapper_QSM_FANSI',...
                           'Wrapper_QSM_StarQSM',...
                           'Wrapper_QSM_MEDI',...
                           } ;