%% h = qsmhub_handle_panel_dataIO(hParent,hFig,h,position)
%
% Input
% --------------
%
% Output
% --------------
%
% Description:
%
% Kwok-shing Chan @ DCCN
% k.chan@donders.ru.nl
% Date created: 16 April 2018
% Date last modified: 17 April 2018
%
%
function h = qsmhub_handle_panel_dataIO(hParent,hFig,h,position)
h.StepsPanel.dataIO = uipanel(hParent,'Title','I/O',...
    'Position',[position(1) position(2) 0.95 0.2],...
    'backgroundcolor',get(hFig,'color'));
    h.dataIO.text.input = uicontrol(h.StepsPanel.dataIO,'Style','text','String','Input dir:',...
        'Units','normalized','Position', [0.01 0.8 0.15 0.15],...
        'HorizontalAlignment','left',...
        'backgroundcolor',get(hFig,'color'),...
        'tooltip','Input directory contains DICOM or NIfTI files');
    h.dataIO.edit.input = uicontrol('Parent',h.StepsPanel.dataIO,'Style','edit',...
        'units','normalized','position',[0.16 0.8 0.7 0.15],...
        'HorizontalAlignment','left',...
        'backgroundcolor','white');
    h.dataIO.button.input = uicontrol('Parent',h.StepsPanel.dataIO,'Style','pushbutton','String','open',...
        'units','normalized','position',[0.87 0.8 0.1 0.15],...
        'backgroundcolor','white');
    h.dataIO.text.output = uicontrol('Parent',h.StepsPanel.dataIO,'Style','text','String','Output dir:',...
        'units','normalized','Position',[0.01 0.64 0.15 0.15],...
        'HorizontalAlignment','left',...
        'backgroundcolor',get(hFig,'color'),...
        'tooltip','Output directory');
    h.dataIO.edit.output = uicontrol('Parent',h.StepsPanel.dataIO,'Style','edit',...
        'units','normalized','position',[0.16 0.64 0.7 0.15],...
        'HorizontalAlignment','left',...
        'backgroundcolor','white');
    h.dataIO.button.output = uicontrol('Parent',h.StepsPanel.dataIO,'Style','pushbutton','String','open',...
        'units','normalized','position',[0.87 0.64 0.1 0.15],...
        'backgroundcolor','white');
    h.dataIO.checkbox.brainExtraction = uicontrol('Parent',h.StepsPanel.dataIO,'Style','checkbox','String','FSL brain extraction',...
        'units','normalized','Position',[0.01 0.4 1 0.2],...
        'backgroundcolor',get(hFig,'color'),...
        'tooltip','Use FSL brain extraction (bet)');
    h.dataIO.text.maskdir = uicontrol('Parent',h.StepsPanel.dataIO,'Style','text','String','Brain mask file:',...
        'units','normalized','Position',[0.01 0.25 0.15 0.15],...
        'HorizontalAlignment','left',...
        'backgroundcolor',get(hFig,'color'),...
        'tooltip','Specify mask file (NIfTI_GZ format)');
    h.dataIO.edit.maskdir = uicontrol('Parent',h.StepsPanel.dataIO,'Style','edit',...
        'units','normalized','position',[0.16 0.25 0.7 0.15],...
        'HorizontalAlignment','left',...
        'backgroundcolor','white');
    h.dataIO.button.maskdir = uicontrol('Parent',h.StepsPanel.dataIO,'Style','pushbutton','String','open',...
        'units','normalized','position',[0.87 0.25 0.1 0.15],...
        'backgroundcolor','white');
end