%% h = qsmhub_handle_panel_phaseUnwrap(hParent,hFig,h,position)
%
% Input
% --------------
% hParent       : parent handle of this panel
% hFig          : handle of the GUI
% h             : global structure contains all handles
% position      : position of this panel
%
% Output
% --------------
% h             : global structure contains all new and other handles
%
% Description: This GUI function creates a panel for phase unwrapping method control
%
% Kwok-shing Chan @ DCCN
% k.chan@donders.ru.nl
% Date created: 16 April 2018
% Date modified: 18 April 2018
% Date modified: 24 May 2018
%
%
function h = qsmhub_handle_panel_phaseUnwrap(hParent,hFig,h,position)

% define maximum level of options and spacing between options
nlevel = 5;
spacing = 0.02;
height = (1-(nlevel+1)*spacing)/nlevel;
button = (height+spacing:height+spacing:(height+spacing)*nlevel) - height;

% Parent handle of phase unwrapping panel
h.StepsPanel.phaseUnwrap = uipanel(hParent,'Title','Total field recovery and phase unwrapping',...
    'position',[position(1) position(2) 0.95 0.2]);
    
    % Temporo-spatial unwrapping methods
    h.phaseUnwrap.text.phaseCombMethod = uicontrol('Parent',h.StepsPanel.phaseUnwrap ,...
        'Style','text','String','Echo phase combination',...
        'units','normalized','position',[0.01 button(nlevel) 0.3 height],...
        'HorizontalAlignment','left',...
        'backgroundcolor',get(hFig,'color'),...
        'tooltip','Select method to combine echo phase');
    h.phaseUnwrap.popup.phaseCombMethod = uicontrol('Parent',h.StepsPanel.phaseUnwrap ,...
        'Style','popup',...
        'String',{'Optimum weights','MEDI nonlinear fit'},...
        'units','normalized','position',[0.31 button(nlevel) 0.4 height]); 
    
    % phase unwrapping method
    h.phaseUnwrap.text.phaseUnwrap = uicontrol('Parent',h.StepsPanel.phaseUnwrap ,...
        'Style','text','String','Phase unwrapping:',...
        'units','normalized','position',[0.01 button(nlevel-1) 0.3 height],...
        'HorizontalAlignment','left',...
        'backgroundcolor',get(hFig,'color'),...
        'tooltip','Select phase unwrapping algorithm');
    h.phaseUnwrap.popup.phaseUnwrap = uicontrol('Parent',h.StepsPanel.phaseUnwrap ,...
        'Style','popup',...
        'String',{'Laplacian','Laplacian STI suite','3D best path','Region growing','Graphcut'},...
        'units','normalized','position',[0.31 button(nlevel-1) 0.4 height]); 
%     h.phaseUnwrap.text.unit = uicontrol('Parent',h.StepsPanel.phaseUnwrap ,'Style','text','String','Output unit:',...
%         'units','normalized','position',[0.01 0.65 0.3 0.15],...
%         'HorizontalAlignment','left',...
%         'backgroundcolor',get(hFig,'color'),...
%         'tooltip','Select unwrapped phase map unit');
%     h.phaseUnwrap.popup.unit = uicontrol('Parent',h.StepsPanel.phaseUnwrap ,'Style','popup',...
%         'String',{'radHz','ppm','rad','Hz'},...
%         'units','normalized','position',[0.31 0.65 0.4 0.15]);

    % eddy current correction for bipolar readout
    h.phaseUnwrap.checkbox.eddyCorrect = uicontrol('Parent',h.StepsPanel.phaseUnwrap ,...
        'Style','checkbox','String','Bipolar readout eddy current correction',...
        'units','normalized','Position',[0.01 button(nlevel-2) 1 height],...
        'backgroundcolor',get(hFig,'color'),...
        'tooltip','Correct inconsistent phase between odd and even echoes');
    
    % exclusion of unreliable voxels
    h.phaseUnwrap.checkbox.excludeMask = uicontrol('Parent',h.StepsPanel.phaseUnwrap ,...
        'Style','checkbox','String','Exclude unreliable voxels',...
        'units','normalized','position',[0.01 button(nlevel-3) 0.6 height],...
        'backgroundcolor',get(hFig,'color'),...
        'tooltip','Apply threshold to exclude unreliable voxels based on relative residual of monodecay model with a single frequency shift');
    h.phaseUnwrap.text.excludeMask = uicontrol('Parent',h.StepsPanel.phaseUnwrap ,...
        'Style','text','String','Threshold',...
        'units','normalized','position',[0.01 button(nlevel-4) 0.3 height],...
        'HorizontalAlignment','left',...
        'backgroundcolor',get(hFig,'color'),...
        'tooltip','Higher value means accepting greater mismatch between the esimtation and measurement');
    h.phaseUnwrap.edit.excludeMask = uicontrol('Parent',h.StepsPanel.phaseUnwrap ,...
        'Style','edit',...
        'String','0.5',...
        'units','normalized','position',[0.31 button(nlevel-4) 0.3 height],...
        'backgroundcolor','white',...
        'Enable','off');
        
end