%% h = qsmhub_handle_panel_utility_mask_ventricle(hParent,hFig,h,position)
%
% Input
% --------------
% hParent       : parent handle of this panel
% hFig          : handle of the GUI
% h             : global structure contains all handles
% position      : position of this panel
%
% Output
% --------------
% h             : global structure contains all new and other handles
%
% Description: This GUI function creates a panel for the utility function
% 'Get ventricle mask'
%
% Kwok-shing Chan @ DCCN
% k.chan@donders.ru.nl
% Date created: 25 May 2018
% Date last modified: 
%
%
function h = qsmhub_handle_panel_utility_mask_ventricle(hParent,h,position)
% set Parent of all related controls
h.StepsPanel.Utility.csfMask = uipanel(hParent,'Title','2. Get ventricle mask',...
    'Position',[position(1) position(2) 0.95 0.25],...
    'backgroundcolor',get(h.fig,'color'));
    
    % NIfTI file input
    h.Utility.csfMask.text.niftiInput = uicontrol(h.StepsPanel.Utility.csfMask,...
        'Style','text','String','mGRE magnitude',...
        'Units','normalized','Position', [0.01 0.85 0.2 0.14],...
        'HorizontalAlignment','left',...
        'backgroundcolor',get(h.fig,'color'),...
        'tooltip','Multi-echo GRE (4D) magnitude NIfTI file.');
    h.Utility.csfMask.edit.niftiInput = uicontrol('Parent',h.StepsPanel.Utility.csfMask,...
        'Style','edit',...
        'units','normalized','position',[0.21 0.85 0.68 0.14],...
        'HorizontalAlignment','left',...
        'backgroundcolor','white');
    h.Utility.csfMask.button.niftiInput = uicontrol('Parent',h.StepsPanel.Utility.csfMask,...
        'Style','pushbutton','String','open',...
        'units','normalized','position',[0.89 0.85 0.1 0.14],...
        'backgroundcolor','white');
    
    % mask file input
    h.Utility.csfMask.text.maskInput = uicontrol(h.StepsPanel.Utility.csfMask,...
        'Style','text','String','Brain mask',...
        'Units','normalized','Position', [0.01 0.70 0.2 0.14],...
        'HorizontalAlignment','left',...
        'backgroundcolor',get(h.fig,'color'),...
        'tooltip','Brain mask NIfTI file (optional)');
    h.Utility.csfMask.edit.maskInput = uicontrol('Parent',h.StepsPanel.Utility.csfMask,...
        'Style','edit',...
        'units','normalized','position',[0.21 0.70 0.68 0.14],...
        'HorizontalAlignment','left',...
        'backgroundcolor','white');
    h.Utility.csfMask.button.maskInput = uicontrol('Parent',h.StepsPanel.Utility.csfMask,...
        'Style','pushbutton','String','open',...
        'units','normalized','position',[0.89 0.70 0.1 0.14],...
        'backgroundcolor','white');
    
    % TE
    % TE file
    h.Utility.csfMask.text.teFile = uicontrol('Parent',h.StepsPanel.Utility.csfMask,...
        'Style','text','String','TE file',...
        'units','normalized','Position',[0.01 0.55 0.2 0.14],...
        'HorizontalAlignment','left',...
        'backgroundcolor',get(h.fig,'color'),...
        'tooltip','Can be either qsm_hub header (.mat) or MRIConvert text (.txt) file');
    h.Utility.csfMask.edit.teFile = uicontrol('Parent',h.StepsPanel.Utility.csfMask,...
        'Style','edit',...
        'units','normalized','position',[0.21 0.55 0.68 0.14],...
        'HorizontalAlignment','left',...
        'backgroundcolor','white');
    h.Utility.csfMask.button.teFile = uicontrol('Parent',h.StepsPanel.Utility.csfMask,...
        'Style','pushbutton','String','open',...
        'units','normalized','position',[0.89 0.55 0.1 0.14],...
        'backgroundcolor','white');
    % user TE input
    h.Utility.csfMask.text.userTE = uicontrol('Parent',h.StepsPanel.Utility.csfMask,...
        'Style','text','String','or user input TEs (s)',...
        'units','normalized','Position',[0.01 0.4 0.2 0.14],...
        'HorizontalAlignment','left',...
        'backgroundcolor',get(h.fig,'color'),...
        'tooltip','Specify the echo time (TE, in s) of each echo');
    h.Utility.csfMask.edit.userTE = uicontrol('Parent',h.StepsPanel.Utility.csfMask,...
        'Style','edit',...
        'units','normalized','position',[0.21 0.4 0.78 0.14],...
        'HorizontalAlignment','left',...
        'backgroundcolor','white',...
        'String','[ ]');
    
    % output directory
    h.Utility.csfMask.text.outputDir = uicontrol(h.StepsPanel.Utility.csfMask,...
        'Style','text','String','Output dir:',...
        'Units','normalized','Position', [0.01 0.25 0.2 0.14],...
        'HorizontalAlignment','left',...
        'backgroundcolor',get(h.fig,'color'),...
        'tooltip','Output directory where the output mask file will be stored');
    h.Utility.csfMask.edit.outputDir = uicontrol('Parent',h.StepsPanel.Utility.csfMask,...
        'Style','edit',...
        'units','normalized','position',[0.21 0.25 0.68 0.14],...
        'HorizontalAlignment','left',...
        'backgroundcolor','white');
    h.Utility.csfMask.button.outputDir = uicontrol('Parent',h.StepsPanel.Utility.csfMask,...
        'Style','pushbutton','String','open',...
        'units','normalized','position',[0.89 0.25 0.1 0.14],...
        'backgroundcolor','white');
    
    % run
    h.Utility.csfMask.button.run = uicontrol('Parent',h.StepsPanel.Utility.csfMask,...
        'Style','pushbutton','String','Run',...
        'units','normalized','position',[0.89 0.05 0.1 0.18],...
        'backgroundcolor','white');
    
end