%% h = qsmhub_handle_panel_qsm_STIiLSQR(hParent,h,position)
%
% Input
% --------------
% hParent       : parent handle of this panel
% h             : global structure contains all handles
% position      : position of this panel
%
% Output
% --------------
% h             : global structure contains all new and other handles
%
% Description: This GUI function creates a panel for STIiLSQR method
%
% Kwok-shing Chan @ DCCN
% k.chan@donders.ru.nl
% Date created: 1 June 2018
% Date last modified: 
%
%
function h = qsmhub_handle_panel_qsm_STIiLSQR(hParent,h,position)

%% Parent handle of CFS panel children

h.qsm.panel.STIiLSQR = uipanel(hParent,...
    'Title','STI suite iLSQR',...
    'position',position,...
    'backgroundcolor',get(h.fig,'color'),'Visible','off');

%% Children of CFS panel
    
    % text|edit field pair: threshold
    h.qsm.STIiLSQR.text.threshold = uicontrol('Parent',h.qsm.panel.STIiLSQR,...
        'Style','text',...
        'String','Threshold:',...
        'units','normalized','position',[0.01 0.75 0.2 0.2],...
        'HorizontalAlignment','left',...
        'backgroundcolor',get(h.fig,'color'));
    h.qsm.STIiLSQR.edit.threshold = uicontrol('Parent',h.qsm.panel.STIiLSQR,...
        'Style','edit',...
        'String','0.01',...
        'units','normalized','position',[0.25 0.75 0.2 0.2],...
        'backgroundcolor','white');

	% text|edit field pair: maximum iterations
    h.qsm.STIiLSQR.text.maxIter = uicontrol('Parent',h.qsm.panel.STIiLSQR,...
        'Style','text',...
        'String','Iterations:',...
        'units','normalized','position',[0.01 0.5 0.2 0.2],...
        'HorizontalAlignment','left',...
        'backgroundcolor',get(h.fig,'color'));
    h.qsm.STIiLSQR.edit.maxIter = uicontrol('Parent',h.qsm.panel.STIiLSQR,...
        'Style','edit',...
        'String','100',...
        'units','normalized','position',[0.25 0.5 0.2 0.2],...
        'backgroundcolor','white');

	% text|edit field pair: tolerance 1
    h.qsm.STIiLSQR.text.tol1 = uicontrol('Parent',h.qsm.panel.STIiLSQR,...
        'Style','text',...
        'String','Tolerance 1:',...
        'units','normalized','position',[0.01 0.25 0.2 0.2],...
        'HorizontalAlignment','left',...
        'backgroundcolor',get(h.fig,'color'));
    h.qsm.STIiLSQR.edit.tol1 = uicontrol('Parent',h.qsm.panel.STIiLSQR,...
        'Style','edit',...
        'String','0.01',...
        'units','normalized','position',[0.25 0.25 0.2 0.2],...
        'backgroundcolor','white');

    % text|edit field pair: tolerance 2
    h.qsm.STIiLSQR.text.tol2 = uicontrol('Parent',h.qsm.panel.STIiLSQR,...
        'Style','text',...
        'String','Tolerance 2:',...
        'units','normalized','position',[0.5 0.25 0.2 0.2],...
        'HorizontalAlignment','left',...
        'backgroundcolor',get(h.fig,'color'));
    h.qsm.STIiLSQR.edit.tol2 = uicontrol('Parent',h.qsm.panel.STIiLSQR,...
        'Style','edit',...
        'String','0.001',...
        'units','normalized','position',[0.75 0.25 0.2 0.2],...
        'backgroundcolor','white');

    % text|edit field pair: pad size
    h.qsm.STIiLSQR.text.padSize = uicontrol('Parent',h.qsm.panel.STIiLSQR,...
        'Style','text',...
        'String','Pad size:',...
        'units','normalized','position',[0.01 0.01 0.2 0.2],...
        'HorizontalAlignment','left',...
        'backgroundcolor',get(h.fig,'color'));
    h.qsm.STIiLSQR.edit.padSize = uicontrol('Parent',h.qsm.panel.STIiLSQR,...
        'Style','edit',...
        'String','12',...
        'units','normalized','position',[0.25 0.01 0.2 0.2],...
        'backgroundcolor','white');

end