%% h = qsmhub_handle_panel_utility_get_header(hParent,hFig,h,position)
%
% Input
% --------------
% hParent       : parent handle of this panel
% hFig          : handle of the GUI
% h             : global structure contains all handles
% position      : position of this panel
%
% Output
% --------------
% h             : global structure contains all new and other handles
%
% Description: This GUI function creates a panel for the utility function
% 'Get qsm_hub header'
%
% Kwok-shing Chan @ DCCN
% k.chan@donders.ru.nl
% Date created: 25 May 2018
% Date last modified: 
%
%
function h = qsmhub_handle_panel_utility_mask_ventricle(hParent,hFig,h,position)
% set Parent of all related controls
h.StepsPanel.Utility.csfMask = uipanel(hParent,'Title','2. Get ventricle mask',...
    'Position',[position(1) position(2) 0.95 0.25],...
    'backgroundcolor',get(hFig,'color'));

    % DICOM directory input
%     h.Utility.csfMask.text.dicomInput = uicontrol(h.StepsPanel.Utility.csfMask,...
%         'Style','text','String','Input DICOM dir:',...
%         'Units','normalized','Position', [0.01 0.88 0.2 0.1],...
%         'HorizontalAlignment','left',...
%         'backgroundcolor',get(hFig,'color'),...
%         'tooltip',...
%         strcat('Input directory contains all (magnitude and phase) mGRE DICOM files. ',...
%          'No user input will be saved if your data input is a DICOM directory.'));
%     h.Utility.csfMask.edit.dicomInput = uicontrol('Parent',h.StepsPanel.Utility.csfMask,...
%         'Style','edit',...
%         'units','normalized','position',[0.21 0.88 0.68 0.1],...
%         'HorizontalAlignment','left',...
%         'backgroundcolor','white');
%     h.Utility.csfMask.button.dicomInput = uicontrol('Parent',h.StepsPanel.Utility.csfMask,...
%         'Style','pushbutton','String','open',...
%         'units','normalized','position',[0.89 0.88 0.1 0.1],...
%         'backgroundcolor','white');
    
    % NIfTI file input
    h.Utility.csfMask.text.niftiInput = uicontrol(h.StepsPanel.Utility.csfMask,...
        'Style','text','String','mGRE magnitude',...
        'Units','normalized','Position', [0.01 0.85 0.2 0.14],...
        'HorizontalAlignment','left',...
        'backgroundcolor',get(hFig,'color'),...
        'tooltip','Input NIfTI file of mGRE data. User input is allowed');
    h.Utility.csfMask.edit.niftiInput = uicontrol('Parent',h.StepsPanel.Utility.csfMask,...
        'Style','edit',...
        'units','normalized','position',[0.21 0.85 0.68 0.14],...
        'HorizontalAlignment','left',...
        'backgroundcolor','white');
    h.Utility.csfMask.button.niftiInput = uicontrol('Parent',h.StepsPanel.Utility.csfMask,...
        'Style','pushbutton','String','open',...
        'units','normalized','position',[0.89 0.85 0.1 0.14],...
        'backgroundcolor','white');
    
    % mask file input
    h.Utility.csfMask.text.maskInput = uicontrol(h.StepsPanel.Utility.csfMask,...
        'Style','text','String','Brain mask',...
        'Units','normalized','Position', [0.01 0.70 0.2 0.14],...
        'HorizontalAlignment','left',...
        'backgroundcolor',get(hFig,'color'),...
        'tooltip','Input mask file in NIfTI format');
    h.Utility.csfMask.edit.maskInput = uicontrol('Parent',h.StepsPanel.Utility.csfMask,...
        'Style','edit',...
        'units','normalized','position',[0.21 0.70 0.68 0.14],...
        'HorizontalAlignment','left',...
        'backgroundcolor','white');
    h.Utility.csfMask.button.maskInput = uicontrol('Parent',h.StepsPanel.Utility.csfMask,...
        'Style','pushbutton','String','open',...
        'units','normalized','position',[0.89 0.70 0.1 0.14],...
        'backgroundcolor','white');
    
    % TE
    % TE file
    h.Utility.csfMask.text.teFile = uicontrol('Parent',h.StepsPanel.Utility.csfMask,...
        'Style','text','String','TE file',...
        'units','normalized','Position',[0.01 0.55 0.2 0.14],...
        'HorizontalAlignment','left',...
        'backgroundcolor',get(hFig,'color'),...
        'tooltip','TE file can be .mat or .txt');
    h.Utility.csfMask.edit.teFile = uicontrol('Parent',h.StepsPanel.Utility.csfMask,...
        'Style','edit',...
        'units','normalized','position',[0.21 0.55 0.68 0.14],...
        'HorizontalAlignment','left',...
        'backgroundcolor','white');
    h.Utility.csfMask.button.teFile = uicontrol('Parent',h.StepsPanel.Utility.csfMask,...
        'Style','pushbutton','String','open',...
        'units','normalized','position',[0.89 0.55 0.1 0.14],...
        'backgroundcolor','white');
    % user TE input
    h.Utility.csfMask.text.userTE = uicontrol('Parent',h.StepsPanel.Utility.csfMask,...
        'Style','text','String','or user input TEs (s)',...
        'units','normalized','Position',[0.01 0.4 0.2 0.14],...
        'HorizontalAlignment','left',...
        'backgroundcolor',get(hFig,'color'),...
        'tooltip','Specify the echo times (in s) of each echo');
    h.Utility.csfMask.edit.userTE = uicontrol('Parent',h.StepsPanel.Utility.csfMask,...
        'Style','edit',...
        'units','normalized','position',[0.21 0.4 0.78 0.18],...
        'HorizontalAlignment','left',...
        'backgroundcolor','white',...
        'String','[ ]');
    
    % output directory
    h.Utility.csfMask.text.outputDir = uicontrol(h.StepsPanel.Utility.csfMask,...
        'Style','text','String','Output dir:',...
        'Units','normalized','Position', [0.01 0.25 0.2 0.14],...
        'HorizontalAlignment','left',...
        'backgroundcolor',get(hFig,'color'),...
        'tooltip','Output directory that store the header file');
    h.Utility.csfMask.edit.outputDir = uicontrol('Parent',h.StepsPanel.Utility.csfMask,...
        'Style','edit',...
        'units','normalized','position',[0.21 0.25 0.68 0.14],...
        'HorizontalAlignment','left',...
        'backgroundcolor','white');
    h.Utility.csfMask.button.outputDir = uicontrol('Parent',h.StepsPanel.Utility.csfMask,...
        'Style','pushbutton','String','open',...
        'units','normalized','position',[0.89 0.25 0.1 0.14],...
        'backgroundcolor','white');
    
    % run
    h.Utility.csfMask.button.run = uicontrol('Parent',h.StepsPanel.Utility.csfMask,...
        'Style','pushbutton','String','Run',...
        'units','normalized','position',[0.89 0.05 0.1 0.18],...
        'backgroundcolor','white');
    
end