%% function output = function_name(input)
%
% Usage:
%
% Input
% --------------
%
% Output
% --------------
%
% Description:
%
% Kwok-shing Chan @ DCCN
% k.chan@donders.ru.nl
% Date created: 
% Date last modified:
%
%
function h = qsmhub_handle_panel_bkgRemoval(hParent,hFig,h,position)
h.panel_bkgRemoval = uipanel(hParent,'Title','Background field removal',...
    'position',[position(1) position(2) 0.95 0.25],...
    'backgroundcolor',get(hFig,'color'));
    h.text_bkgRemoval = uicontrol('Parent',h.panel_bkgRemoval,'Style','text','String','Method:',...
        'units','normalized','position',[0.01 0.85 0.3 0.1],...
        'HorizontalAlignment','left',...
        'backgroundcolor',get(hFig,'color'),...
        'tooltip','Select background field removal method');
    h.popup_bkgRemoval = uicontrol('Parent',h.panel_bkgRemoval,'Style','popup',...
        'String',{'LBV','PDF','RESHARP','SHARP','VSHARP STI suite','VSHARP','iHARPERELLA'},...
        'units','normalized','position',[0.31 0.85 0.4 0.1]) ;   
    h.checkbox_bkgRemoval = uicontrol('Parent',h.panel_bkgRemoval,'Style','checkbox','String','Refine local field by polynomial fit',...
        'units','normalized','position',[0.01 0.01 1 0.1],...
        'backgroundcolor',get(hFig,'color'),...
        'tooltip','Enable to remove residual B1 field inhomogeneity',...
        'value',1);
    
    % LBV
    h.panel_bkgRemoval_LBV = uipanel(h.panel_bkgRemoval,'Title','Laplacian boundary value (LBV)',...
        'position',[0.01 0.15 0.95 0.65],...
        'backgroundcolor',get(hFig,'color'));
        h.text_LBV_tol = uicontrol('Parent',h.panel_bkgRemoval_LBV,'Style','text',...
            'String','Tolerance:',...
            'units','normalized','position',[0.01 0.75 0.2 0.2],...
            'HorizontalAlignment','left',...
            'backgroundcolor',get(hFig,'color'),...
            'tooltip','Iteration stopping criteria on the coarsest grid');
        h.edit_LBV_tol = uicontrol('Parent',h.panel_bkgRemoval_LBV,'Style','edit',...
            'String','0.01',...
            'units','normalized','position',[0.25 0.75 0.2 0.2],...
            'backgroundcolor','white');
        h.text_LBV_depth = uicontrol('Parent',h.panel_bkgRemoval_LBV,'Style','text',...
            'String','Depth:',...
            'units','normalized','position',[0.01 0.5 0.2 0.2],...
            'HorizontalAlignment','left',...
            'backgroundcolor',get(hFig,'color'),...
            'tooltip','Multigrid level: The largest length scale is 2^depth * voxel size');
        h.edit_LBV_depth = uicontrol('Parent',h.panel_bkgRemoval_LBV,'Style','edit',...
            'String','5',...
            'units','normalized','position',[0.25 0.5 0.2 0.2],...
            'backgroundcolor','white');
        h.text_LBV_peel = uicontrol('Parent',h.panel_bkgRemoval_LBV,'Style','text',...
            'String','Peel:',...
            'units','normalized','position',[0.01 0.25 0.2 0.2],...
            'HorizontalAlignment','left',...
            'backgroundcolor',get(hFig,'color'),...
            'tooltip','No. of boundary layers to be peeled off');
        h.edit_LBV_peel = uicontrol('Parent',h.panel_bkgRemoval_LBV,'Style','edit',...
            'String','2',...
            'units','normalized','position',[0.25 0.25 0.2 0.2],...
            'backgroundcolor','white');
        
    % PDF
    h.panel_bkgRemoval_PDF = uipanel(h.panel_bkgRemoval,'Title','Projection onto dipole field (PDF)',...
        'position',[0.01 0.15 0.95 0.65],...
        'backgroundcolor',get(hFig,'color'),'Visible','off');
        h.text_PDF_tol = uicontrol('Parent',h.panel_bkgRemoval_PDF,'Style','text',...
            'String','Tolerance:',...
            'units','normalized','position',[0.01 0.75 0.2 0.2],...
            'HorizontalAlignment','left',...
            'backgroundcolor',get(hFig,'color'));
        h.edit_PDF_tol = uicontrol('Parent',h.panel_bkgRemoval_PDF,'Style','edit',...
            'String','0.1',...
            'units','normalized','position',[0.25 0.75 0.2 0.2],...
            'backgroundcolor','white');
        h.text_PDF_maxIter = uicontrol('Parent',h.panel_bkgRemoval_PDF,'Style','text',...
            'String','Iterations:',...
            'units','normalized','position',[0.01 0.5 0.2 0.2],...
            'HorizontalAlignment','left',...
            'backgroundcolor',get(hFig,'color'),...
            'tooltip','Maximum iterations');
        h.edit_PDF_maxIter = uicontrol('Parent',h.panel_bkgRemoval_PDF,'Style','edit',...
            'String','50',...
            'units','normalized','position',[0.25 0.5 0.2 0.2],...
            'backgroundcolor','white');
        h.text_PDF_padSize = uicontrol('Parent',h.panel_bkgRemoval_PDF,'Style','text',...
            'String','Zero pad size:',...
            'units','normalized','position',[0.01 0.25 0.23 0.2],...
            'HorizontalAlignment','left',...
            'backgroundcolor',get(hFig,'color'),...
            'tooltip','No. of zeros to be added');
        h.edit_PDF_padSize = uicontrol('Parent',h.panel_bkgRemoval_PDF,'Style','edit',...
            'String','40',...
            'units','normalized','position',[0.25 0.25 0.2 0.2],...
            'backgroundcolor','white');
%         h.text_PDF_cgSolver = uicontrol('Parent',h.panel_bkgRemoval_PDF,'Style','text',...
%             'String','CG solver',...
%             'units','normalized','position',[0.01 0.25 0.2 0.2],...
%             'HorizontalAlignment','left',...
%             'backgroundcolor',get(hFig,'color'),...
%             'tooltip','Select CG solver');
%         h.popup_PDF_cgSolver = uicontrol('Parent',h.panel_bkgRemoval_PDF,'Style','popup',...
%             'String',{'MEDI cgsolver','Matlab pcg'},...
%             'units','normalized','position',[0.25 0.25 0.5 0.2]);
        
    % SHARP
    h.panel_bkgRemoval_SHARP = uipanel(h.panel_bkgRemoval,'Title','SHARP',...
        'position',[0.01 0.15 0.95 0.65],...
        'backgroundcolor',get(hFig,'color'),'Visible','off');
        h.text_SHARP_radius = uicontrol('Parent',h.panel_bkgRemoval_SHARP,'Style','text',...
            'String','Radius:',...
            'units','normalized','position',[0.01 0.75 0.2 0.2],...
            'HorizontalAlignment','left',...
            'backgroundcolor',get(hFig,'color'),...
            'tooltip','Radius of sphere; unit in voxel');
        h.edit_SHARP_radius = uicontrol('Parent',h.panel_bkgRemoval_SHARP,'Style','edit',...
            'String','4',...
            'units','normalized','position',[0.25 0.75 0.2 0.2],...
            'backgroundcolor','white');
        h.text_SHARP_threshold = uicontrol('Parent',h.panel_bkgRemoval_SHARP,'Style','text',...
            'String','Threshold:',...
            'units','normalized','position',[0.01 0.5 0.2 0.2],...
            'HorizontalAlignment','left',...
            'backgroundcolor',get(hFig,'color'),...
            'tooltip','Threshold used in truncated SVD');
        h.edit_SHARP_threshold = uicontrol('Parent',h.panel_bkgRemoval_SHARP,'Style','edit',...
            'String','0.03',...
            'units','normalized','position',[0.25 0.5 0.2 0.2],...
            'backgroundcolor','white');
    
    % RESHARP    
    h.panel_bkgRemoval_RESHARP = uipanel(h.panel_bkgRemoval,'Title','Regularisation SHARP',...
        'position',[0.01 0.15 0.95 0.65],...
        'backgroundcolor',get(hFig,'color'),'Visible','off');
        h.text_RESHARP_radius = uicontrol('Parent',h.panel_bkgRemoval_RESHARP,'Style','text',...
            'String','Radius:',...
            'units','normalized','position',[0.01 0.75 0.2 0.2],...
            'HorizontalAlignment','left',...
            'backgroundcolor',get(hFig,'color'));
        h.edit_RESHARP_radius = uicontrol('Parent',h.panel_bkgRemoval_RESHARP,'Style','edit',...
            'String','4',...
            'units','normalized','position',[0.25 0.75 0.2 0.2],...
            'backgroundcolor','white');
        h.text_RESHARP_lambda = uicontrol('Parent',h.panel_bkgRemoval_RESHARP,'Style','text',...
            'String','Regularisation:',...
            'units','normalized','position',[0.01 0.5 0.2 0.2],...
            'HorizontalAlignment','left',...
            'backgroundcolor',get(hFig,'color'));
        h.edit_RESHARP_lambda = uicontrol('Parent',h.panel_bkgRemoval_RESHARP,'Style','edit',...
            'String','0.01',...
            'units','normalized','position',[0.25 0.5 0.2 0.2],...
            'backgroundcolor','white');
        
    % VSHARPSTI    
    h.panel_bkgRemoval_VSHARPSTI = uipanel(h.panel_bkgRemoval,'Title','STI suite Variable SHARP',...
        'position',[0.01 0.15 0.95 0.65],...
        'backgroundcolor',get(hFig,'color'),'Visible','off');
        h.text_VSHARPSTI_smvSize = uicontrol('Parent',h.panel_bkgRemoval_VSHARPSTI,'Style','text',...
            'String','SMV size (mm):',...
            'units','normalized','position',[0.01 0.75 0.2 0.2],...
            'HorizontalAlignment','left',...
            'backgroundcolor',get(hFig,'color'));
        h.edit_VSHARPSTI_smvSize = uicontrol('Parent',h.panel_bkgRemoval_VSHARPSTI,'Style','edit',...
            'String','12',...
            'units','normalized','position',[0.25 0.75 0.2 0.2],...
            'backgroundcolor','white');
    
    % VSHARP
    h.panel_bkgRemoval_VSHARP = uipanel(h.panel_bkgRemoval,'Title','Variable SHARP',...
        'position',[0.01 0.15 0.95 0.65],...
        'backgroundcolor',get(hFig,'color'),'Visible','off');
        h.text_VSHARP_maxRadius = uicontrol('Parent',h.panel_bkgRemoval_VSHARP,'Style','text',...
            'String','Max. radius:',...
            'units','normalized','position',[0.01 0.75 0.2 0.2],...
            'HorizontalAlignment','left',...
            'backgroundcolor',get(hFig,'color'));
        h.edit_VSHARP_maxRadius = uicontrol('Parent',h.panel_bkgRemoval_VSHARP,'Style','edit',...
            'String','10',...
            'units','normalized','position',[0.25 0.75 0.2 0.2],...
            'backgroundcolor','white');
        h.text_VSHARP_minRadius = uicontrol('Parent',h.panel_bkgRemoval_VSHARP,'Style','text',...
            'String','Min. radius:',...
            'units','normalized','position',[0.01 0.5 0.2 0.2],...
            'HorizontalAlignment','left',...
            'backgroundcolor',get(hFig,'color'));
        h.edit_VSHARP_minRadius = uicontrol('Parent',h.panel_bkgRemoval_VSHARP,'Style','edit',...
            'String','3',...
            'units','normalized','position',[0.25 0.5 0.2 0.2],...
            'backgroundcolor','white');
        
    % iHARPERELLA    
    h.panel_bkgRemoval_iHARPERELLA = uipanel(h.panel_bkgRemoval,'Title','iHARPERELLA',...
        'position',[0.01 0.15 0.95 0.65],...
        'backgroundcolor',get(hFig,'color'),'Visible','off');
        h.text_iHARPERELLA_maxIter = uicontrol('Parent',h.panel_bkgRemoval_iHARPERELLA,'Style','text',...
            'String','Max. iterations:',...
            'units','normalized','position',[0.01 0.75 0.2 0.2],...
            'HorizontalAlignment','left',...
            'backgroundcolor',get(hFig,'color'));
        h.edit_iHARPERELLA_maxIter = uicontrol('Parent',h.panel_bkgRemoval_iHARPERELLA,'Style','edit',...
            'String','100',...
            'units','normalized','position',[0.25 0.75 0.2 0.2],...
            'backgroundcolor','white');
end