%% function output = function_name(input)
%
% Usage:
%
% Input
% --------------
%
% Output
% --------------
%
% Description:
%
% Kwok-shing Chan @ DCCN
% k.chan@donders.ru.nl
% Date created: 
% Date last modified:
%
%
function h = qsmhub_handle_panel_qsm(hParent,hFig,h,position)
h.panel_qsm = uipanel(hParent,'Title','QSM','backgroundcolor',get(hFig,'color'),...
    'position',[position(1) position(2) 0.95 0.25]);
    h.text_qsm = uicontrol('Parent',h.panel_qsm,'Style','text','String','Method:',...
        'units','normalized','position',[0.01 0.85 0.15 0.1],...
        'HorizontalAlignment','left',...
        'backgroundcolor',get(hFig,'color'));
    h.popup_qsm = uicontrol('Parent',h.panel_qsm,'Style','popup',...
        'String',{'TKD','Closed-form solution','STI suite iLSQR','iLSQR','FANSI','Star','MEDI'},...
        'units','normalized','position',[0.31 0.85 0.4 0.1]) ; 
    
    % TKD    
    h.panel_qsm_TKD = uipanel(h.panel_qsm,'Title','Thresholded k-space division (TKD)',...
        'position',[0.01 0.04 0.95 0.75],...
        'backgroundcolor',get(hFig,'color'),'Visible','on');
        h.text_TKD_threshold = uicontrol('Parent',h.panel_qsm_TKD,'Style','text',...
            'String','Threshold (0-1):',...
            'units','normalized','position',[0.01 0.75 0.23 0.2],...
            'HorizontalAlignment','left',...
            'backgroundcolor',get(hFig,'color'));
        h.edit_TKD_threshold = uicontrol('Parent',h.panel_qsm_TKD,'Style','edit',...
            'String','0.15',...
            'units','normalized','position',[0.25 0.75 0.2 0.2],...
            'backgroundcolor','white');

    % Closed-form solution  
    h.panel_qsm_cfs = uipanel(h.panel_qsm,'Title','Closed-form solution with L2-norm regularisation',...
        'position',[0.01 0.04 0.95 0.75],...
        'backgroundcolor',get(hFig,'color'),'Visible','off');
        h.text_cfs_lambda = uicontrol('Parent',h.panel_qsm_cfs,'Style','text',...
            'String','Lambda:',...
            'units','normalized','position',[0.01 0.75 0.2 0.2],...
            'HorizontalAlignment','left',...
            'backgroundcolor',get(hFig,'color'));
        h.edit_cfs_lambda = uicontrol('Parent',h.panel_qsm_cfs,'Style','edit',...
            'String','0.13',...
            'units','normalized','position',[0.25 0.75 0.2 0.2],...
            'backgroundcolor','white');
        h.checkbox_cfs_lambda = uicontrol('Parent',h.panel_qsm_cfs,'Style','checkbox',...
            'String','Self-optimisation by L-curve approach',...
            'units','normalized','position',[0.01 0.5 1 0.2],...
            'backgroundcolor',get(hFig,'color'));
    
    % iLSQR  
    h.panel_qsm_iLSQR = uipanel(h.panel_qsm,'Title','Iterative LSQR',...
        'position',[0.01 0.04 0.95 0.75],...
        'backgroundcolor',get(hFig,'color'),'Visible','off');
        h.text_iLSQR_tol = uicontrol('Parent',h.panel_qsm_iLSQR,'Style','text',...
            'String','Tolerance:',...
            'units','normalized','position',[0.01 0.75 0.2 0.2],...
            'HorizontalAlignment','left',...
            'backgroundcolor',get(hFig,'color'));
        h.edit_iLSQR_tol = uicontrol('Parent',h.panel_qsm_iLSQR,'Style','edit',...
            'String','0.001',...
            'units','normalized','position',[0.25 0.75 0.2 0.2],...
            'backgroundcolor','white');
        h.text_iLSQR_maxIter = uicontrol('Parent',h.panel_qsm_iLSQR,'Style','text',...
            'String','Iterations:',...
            'units','normalized','position',[0.01 0.5 0.2 0.2],...
            'HorizontalAlignment','left',...
            'backgroundcolor',get(hFig,'color'));
        h.edit_iLSQR_maxIter = uicontrol('Parent',h.panel_qsm_iLSQR,'Style','edit',...
            'String','100',...
            'units','normalized','position',[0.25 0.5 0.2 0.2],...
            'backgroundcolor','white');
        h.text_iLSQR_lambda = uicontrol('Parent',h.panel_qsm_iLSQR,'Style','text',...
            'String','Lambda:',...
            'units','normalized','position',[0.01 0.25 0.2 0.2],...
            'HorizontalAlignment','left',...
            'backgroundcolor',get(hFig,'color'));
        h.edit_iLSQR_lambda = uicontrol('Parent',h.panel_qsm_iLSQR,'Style','edit',...
            'String','0.13',...
            'units','normalized','position',[0.25 0.25 0.2 0.2],...
            'backgroundcolor','white');
        h.checkbox_iLSQR_lambda = uicontrol('Parent',h.panel_qsm_iLSQR,'Style','checkbox',...
            'String','Self-optimisation by L-curve approach',...
            'units','normalized','position',[0.01 0.01 1 0.2],...
            'backgroundcolor',get(hFig,'color'));
        
    % STI suite iLSQR  
    h.panel_qsm_STIiLSQR = uipanel(h.panel_qsm,'Title','STI suite iLSQR',...
        'position',[0.01 0.04 0.95 0.75],...
        'backgroundcolor',get(hFig,'color'),'Visible','off');
        h.text_STIiLSQR_threshold = uicontrol('Parent',h.panel_qsm_STIiLSQR,'Style','text',...
            'String','Threshold:',...
            'units','normalized','position',[0.01 0.75 0.2 0.2],...
            'HorizontalAlignment','left',...
            'backgroundcolor',get(hFig,'color'));
        h.edit_STIiLSQR_threshold = uicontrol('Parent',h.panel_qsm_STIiLSQR,'Style','edit',...
            'String','0.01',...
            'units','normalized','position',[0.25 0.75 0.2 0.2],...
            'backgroundcolor','white');
        h.text_STIiLSQR_maxIter = uicontrol('Parent',h.panel_qsm_STIiLSQR,'Style','text',...
            'String','Iterations:',...
            'units','normalized','position',[0.01 0.5 0.2 0.2],...
            'HorizontalAlignment','left',...
            'backgroundcolor',get(hFig,'color'));
        h.edit_STIiLSQR_maxIter = uicontrol('Parent',h.panel_qsm_STIiLSQR,'Style','edit',...
            'String','100',...
            'units','normalized','position',[0.25 0.5 0.2 0.2],...
            'backgroundcolor','white');
        h.text_STIiLSQR_tol1 = uicontrol('Parent',h.panel_qsm_STIiLSQR,'Style','text',...
            'String','Tolerance 1:',...
            'units','normalized','position',[0.01 0.25 0.2 0.2],...
            'HorizontalAlignment','left',...
            'backgroundcolor',get(hFig,'color'));
        h.edit_STIiLSQR_tol1 = uicontrol('Parent',h.panel_qsm_STIiLSQR,'Style','edit',...
            'String','0.01',...
            'units','normalized','position',[0.25 0.25 0.2 0.2],...
            'backgroundcolor','white');
        h.text_STIiLSQR_tol2 = uicontrol('Parent',h.panel_qsm_STIiLSQR,'Style','text',...
            'String','Tolerance 2:',...
            'units','normalized','position',[0.5 0.25 0.2 0.2],...
            'HorizontalAlignment','left',...
            'backgroundcolor',get(hFig,'color'));
        h.edit_STIiLSQR_tol2 = uicontrol('Parent',h.panel_qsm_STIiLSQR,'Style','edit',...
            'String','0.001',...
            'units','normalized','position',[0.75 0.25 0.2 0.2],...
            'backgroundcolor','white');
        h.text_STIiLSQR_padSize = uicontrol('Parent',h.panel_qsm_STIiLSQR,'Style','text',...
            'String','Pad size:',...
            'units','normalized','position',[0.01 0.01 0.2 0.2],...
            'HorizontalAlignment','left',...
            'backgroundcolor',get(hFig,'color'));
        h.edit_STIiLSQR_padSize = uicontrol('Parent',h.panel_qsm_STIiLSQR,'Style','edit',...
            'String','12',...
            'units','normalized','position',[0.25 0.01 0.2 0.2],...
            'backgroundcolor','white');
    
    % FANSI
    h.panel_qsm_FANSI = uipanel(h.panel_qsm,'Title','FANSI',...
        'position',[0.01 0.04 0.95 0.75],...
        'backgroundcolor',get(hFig,'color'),'Visible','off');
        h.text_FANSI_tol = uicontrol('Parent',h.panel_qsm_FANSI,'Style','text',...
            'String','Tolerance:',...
            'units','normalized','position',[0.01 0.75 0.2 0.2],...
            'HorizontalAlignment','left',...
            'backgroundcolor',get(hFig,'color'));
        h.edit_FANSI_tol = uicontrol('Parent',h.panel_qsm_FANSI,'Style','edit',...
            'String','1',...
            'units','normalized','position',[0.25 0.75 0.2 0.2],...
            'backgroundcolor','white');
        h.text_FANSI_lambda = uicontrol('Parent',h.panel_qsm_FANSI,'Style','text',...
            'String','L1 penalty:',...
            'units','normalized','position',[0.01 0.5 0.2 0.2],...
            'HorizontalAlignment','left',...
            'backgroundcolor',get(hFig,'color'));
        h.edit_FANSI_lambda = uicontrol('Parent',h.panel_qsm_FANSI,'Style','edit',...
            'String','3e-5',...
            'units','normalized','position',[0.25 0.5 0.2 0.2],...
            'backgroundcolor','white');
        h.text_FANSI_mu = uicontrol('Parent',h.panel_qsm_FANSI,'Style','text',...
            'String','Consistency:',...
            'units','normalized','position',[0.5 0.5 0.2 0.2],...
            'HorizontalAlignment','left',...
            'backgroundcolor',get(hFig,'color'));
        h.edit_FANSI_mu = uicontrol('Parent',h.panel_qsm_FANSI,'Style','edit',...
            'String','5e-5',...
            'units','normalized','position',[0.75 0.5 0.2 0.2],...
            'backgroundcolor','white');
        h.text_FANSI_maxIter = uicontrol('Parent',h.panel_qsm_FANSI,'Style','text',...
            'String','Max. iterations:',...
            'units','normalized','position',[0.01 0.25 0.2 0.2],...
            'HorizontalAlignment','left',...
            'backgroundcolor',get(hFig,'color'));
        h.edit_FANSI_maxIter = uicontrol('Parent',h.panel_qsm_FANSI,'Style','edit',...
            'String','50',...
            'units','normalized','position',[0.25 0.25 0.2 0.2],...
            'backgroundcolor','white');
        h.text_FANSI_solver = uicontrol('Parent',h.panel_qsm_FANSI,'Style','text',...
            'String','Solver:',...
            'units','normalized','position',[0.01 0.01 0.2 0.2],...
            'HorizontalAlignment','left',...
            'backgroundcolor',get(hFig,'color'));
        h.popup_FANSI_solver = uicontrol('Parent',h.panel_qsm_FANSI,'Style','popup',...
            'String',{'Linear','Non-linear'},...
            'units','normalized','position',[0.25 0.01 0.2 0.2],...
            'backgroundcolor','white');
        h.text_FANSI_constraints = uicontrol('Parent',h.panel_qsm_FANSI,'Style','text',...
            'String','Constraint:',...
            'units','normalized','position',[0.5 0.01 0.2 0.2],...
            'HorizontalAlignment','left',...
            'backgroundcolor',get(hFig,'color'));
        h.popup_FANSI_constraints = uicontrol('Parent',h.panel_qsm_FANSI,'Style','popup',...
            'String',{'TV','TGV'},...
            'units','normalized','position',[0.75 0.01 0.2 0.2],...
            'backgroundcolor','white');
        
    % Star
    h.panel_qsm_Star = uipanel(h.panel_qsm,'Title','Star',...
        'position',[0.01 0.04 0.95 0.75],...
        'backgroundcolor',get(hFig,'color'),'Visible','off');
        h.text_Star_padSize = uicontrol('Parent',h.panel_qsm_Star,'Style','text',...
            'String','Pad size:',...
            'units','normalized','position',[0.01 0.75 0.2 0.2],...
            'HorizontalAlignment','left',...
            'backgroundcolor',get(hFig,'color'));
        h.edit_Star_padSize = uicontrol('Parent',h.panel_qsm_Star,'Style','edit',...
            'String','12',...
            'units','normalized','position',[0.25 0.75 0.2 0.2],...
            'backgroundcolor','white');
        
    % MEDI
    h.panel_qsm_MEDI = uipanel(h.panel_qsm,'Title','Morphology-enabled dipole inversion (MEDI)',...
        'position',[0.01 0.04 0.95 0.75],...
        'backgroundcolor',get(hFig,'color'),'Visible','off');
        h.text_MEDI_lambda = uicontrol('Parent',h.panel_qsm_MEDI,'Style','text',...
            'String','lambda:',...
            'units','normalized','position',[0.01 0.75 0.2 0.2],...
            'HorizontalAlignment','left',...
            'backgroundcolor',get(hFig,'color'));
        h.edit_MEDI_lambda = uicontrol('Parent',h.panel_qsm_MEDI,'Style','edit',...
            'String','1000',...
            'units','normalized','position',[0.25 0.75 0.2 0.2],...
            'backgroundcolor','white');
        h.text_MEDI_zeropad = uicontrol('Parent',h.panel_qsm_MEDI,'Style','text',...
            'String','Zeropad:',...
            'units','normalized','position',[0.5 0.75 0.2 0.2],...
            'HorizontalAlignment','left',...
            'backgroundcolor',get(hFig,'color'));
        h.edit_MEDI_zeropad = uicontrol('Parent',h.panel_qsm_MEDI,'Style','edit',...
            'String','0',...
            'units','normalized','position',[0.75 0.75 0.2 0.2],...
            'backgroundcolor','white');
        h.text_MEDI_weightData = uicontrol('Parent',h.panel_qsm_MEDI,'Style','text',...
            'String','Data weight:',...
            'units','normalized','position',[0.01 0.5 0.2 0.2],...
            'HorizontalAlignment','left',...
            'backgroundcolor',get(hFig,'color'));
        h.edit_MEDI_weightData = uicontrol('Parent',h.panel_qsm_MEDI,'Style','edit',...
            'String','1',...
            'units','normalized','position',[0.25 0.5 0.2 0.2],...
            'backgroundcolor','white');
        h.text_MEDI_weightGradient = uicontrol('Parent',h.panel_qsm_MEDI,'Style','text',...
            'String','Gradient weight:',...
            'units','normalized','position',[0.5 0.5 0.24 0.2],...
            'HorizontalAlignment','left',...
            'backgroundcolor',get(hFig,'color'));
        h.edit_MEDI_weightGradient = uicontrol('Parent',h.panel_qsm_MEDI,'Style','edit',...
            'String','1',...
            'units','normalized','position',[0.75 0.5 0.2 0.2],...
            'backgroundcolor','white');
        h.checkbox_MEDI_smv = uicontrol('Parent',h.panel_qsm_MEDI,'Style','checkbox',...
            'String','SMV, radius',...
            'units','normalized','position',[0.01 0.25 0.24 0.2],...
            'HorizontalAlignment','left',...
            'backgroundcolor',get(hFig,'color'));
        h.edit_MEDI_smv_radius = uicontrol('Parent',h.panel_qsm_MEDI,'Style','edit',...
            'String','5',...
            'units','normalized','position',[0.25 0.25 0.2 0.2],...
            'backgroundcolor','white','enable','off');
        h.checkbox_MEDI_merit = uicontrol('Parent',h.panel_qsm_MEDI,'Style','checkbox',...
            'String','Merit',...
            'units','normalized','position',[0.5 0.25 0.24 0.2],...
            'HorizontalAlignment','left',...
            'backgroundcolor',get(hFig,'color'));
        h.checkbox_MEDI_lambda_csf = uicontrol('Parent',h.panel_qsm_MEDI,'Style','checkbox',...
            'String','Lambda CSF:',...
            'units','normalized','position',[0.01 0.01 0.24 0.2],...
            'HorizontalAlignment','left',...
            'backgroundcolor',get(hFig,'color'));
        h.edit_MEDI_lambda_csf = uicontrol('Parent',h.panel_qsm_MEDI,'Style','edit',...
            'String','100',...
            'units','normalized','position',[0.25 0.01 0.2 0.2],...
            'backgroundcolor','white','enable','off');
end