%% function output = function_name(input)
%
% Usage:
%
% Input
% --------------
%
% Output
% --------------
%
% Description:
%
% Kwok-shing Chan @ DCCN
% k.chan@donders.ru.nl
% Date created: 
% Date last modified:
%
%
function h = qsmhub_handle_panel_dataIO(hParent,hFig,h,position)
h.panel_dataIO = uipanel(hParent,'Title','I/O',...
    'Position',[position(1) position(2) 0.95 0.2],...
    'backgroundcolor',get(hFig,'color'));
    h.text_input = uicontrol(h.panel_dataIO,'Style','text','String','Input dir:',...
        'Units','normalized','Position', [0.01 0.8 0.15 0.15],...
        'HorizontalAlignment','left',...
        'backgroundcolor',get(hFig,'color'),...
        'tooltip','Input directory contains DICOM or NIfTI files');
    h.edit_input = uicontrol('Parent',h.panel_dataIO,'Style','edit',...
        'units','normalized','position',[0.16 0.8 0.7 0.15],...
        'HorizontalAlignment','left',...
        'backgroundcolor','white');
    h.button_input = uicontrol('Parent',h.panel_dataIO,'Style','pushbutton','String','open',...
        'units','normalized','position',[0.87 0.8 0.1 0.15],...
        'backgroundcolor','white');
    h.text_output = uicontrol('Parent',h.panel_dataIO,'Style','text','String','Output dir:',...
        'units','normalized','Position',[0.01 0.64 0.15 0.15],...
        'HorizontalAlignment','left',...
        'backgroundcolor',get(hFig,'color'),...
        'tooltip','Output directory');
    h.edit_output = uicontrol('Parent',h.panel_dataIO,'Style','edit',...
        'units','normalized','position',[0.16 0.64 0.7 0.15],...
        'HorizontalAlignment','left',...
        'backgroundcolor','white');
    h.button_output = uicontrol('Parent',h.panel_dataIO,'Style','pushbutton','String','open',...
        'units','normalized','position',[0.87 0.64 0.1 0.15],...
        'backgroundcolor','white');
    h.checkbox_brainExtraction = uicontrol('Parent',h.panel_dataIO,'Style','checkbox','String','FSL brain extraction',...
        'units','normalized','Position',[0.01 0.4 1 0.2],...
        'backgroundcolor',get(hFig,'color'),...
        'tooltip','Use FSL brain extraction (bet)');
    h.text_maskdir = uicontrol('Parent',h.panel_dataIO,'Style','text','String','Brain mask file:',...
        'units','normalized','Position',[0.01 0.25 0.15 0.15],...
        'HorizontalAlignment','left',...
        'backgroundcolor',get(hFig,'color'),...
        'tooltip','Specify mask file (NIfTI_GZ format)');
    h.edit_maskdir = uicontrol('Parent',h.panel_dataIO,'Style','edit',...
        'units','normalized','position',[0.16 0.25 0.7 0.15],...
        'HorizontalAlignment','left',...
        'backgroundcolor','white');
    h.button_maskdir = uicontrol('Parent',h.panel_dataIO,'Style','pushbutton','String','open',...
        'units','normalized','position',[0.87 0.25 0.1 0.15],...
        'backgroundcolor','white');
end