%% h = qsmhub_handle_panel_qsm_iLSQR(hParent,h,position)
%
% Input
% --------------
% hParent       : parent handle of this panel
% h             : global structure contains all handles
% position      : position of this panel
%
% Output
% --------------
% h             : global structure contains all new and other handles
%
% Description: This GUI function creates a panel for iLSQR method
%
% Kwok-shing Chan @ DCCN
% k.chan@donders.ru.nl
% Date created: 1 June 2018
% Date last modified: 
%
%
function h = qsmhub_handle_panel_qsm_iLSQR(hParent,h,position)

%% set default values
defaultTol      = 0.001;
defaultLambda   = 0.13;
defaultMaxIter  = 100;

%% Parent handle of CFS panel children

h.qsm.panel.iLSQR = uipanel(hParent,...
    'Title','Iterative LSQR',...
    'position',position,...
    'backgroundcolor',get(h.fig,'color'),'Visible','off');

%% Children of CFS panel
    
    % text|edit field pair: tolerance
     h.qsm.iLSQR.text.tol = uicontrol('Parent',h.qsm.panel.iLSQR,'Style','text',...
        'String','Tolerance:',...
        'units','normalized','position',[0.01 0.75 0.2 0.2],...
        'HorizontalAlignment','left',...
        'backgroundcolor',get(h.fig,'color'),...
        'tooltip','Relative tolerance to stop LSQR iteration');
    h.qsm.iLSQR.edit.tol = uicontrol('Parent',h.qsm.panel.iLSQR,'Style','edit',...
        'String',num2str(defaultTol),...
        'units','normalized','position',[0.25 0.75 0.2 0.2],...
        'backgroundcolor','white');

    % text|edit field pair: maximum iterations
    h.qsm.iLSQR.text.maxIter = uicontrol('Parent',h.qsm.panel.iLSQR,'Style','text',...
        'String','Max. iterations:',...
        'units','normalized','position',[0.01 0.5 0.2 0.2],...
        'HorizontalAlignment','left',...
        'backgroundcolor',get(h.fig,'color'),...
        'tooltip','Maximum iterations allowed');
    h.qsm.iLSQR.edit.maxIter = uicontrol('Parent',h.qsm.panel.iLSQR,'Style','edit',...
        'String',num2str(defaultMaxIter),...
        'units','normalized','position',[0.25 0.5 0.2 0.2],...
        'backgroundcolor','white');

    % text|edit field pair: regularisation parameter
    h.qsm.iLSQR.text.lambda = uicontrol('Parent',h.qsm.panel.iLSQR,'Style','text',...
        'String','Lambda:',...
        'units','normalized','position',[0.01 0.25 0.2 0.2],...
        'HorizontalAlignment','left',...
        'backgroundcolor',get(h.fig,'color'),...
        'tooltip','Regularisation parameter to control spatial smoothness of QSM');
    h.qsm.iLSQR.edit.lambda = uicontrol('Parent',h.qsm.panel.iLSQR,'Style','edit',...
        'String',num2str(defaultLambda),...
        'units','normalized','position',[0.25 0.25 0.2 0.2],...
        'backgroundcolor','white');

    % checkbox of self-estimated regularisation
    h.qsm.iLSQR.checkbox.lambda = uicontrol('Parent',h.qsm.panel.iLSQR,'Style','checkbox',...
        'String','Self-optimisation by L-curve approach',...
        'units','normalized','position',[0.01 0.01 1 0.2],...
        'backgroundcolor',get(h.fig,'color'),...
        'tooltip','Self estimation of lambda based on L-curve approach');

%% set callbacks
% edit fields
set(h.qsm.iLSQR.edit.lambda,        'Callback',	{@EditInputMinMax_Callback,defaultLambda,   0,0});
set(h.qsm.iLSQR.edit.maxIter,       'Callback',	{@EditInputMinMax_Callback,defaultMaxIter,  1,1});
set(h.qsm.iLSQR.edit.tol,           'Callback',	{@EditInputMinMax_Callback,defaultTol,      0,0});

% checkbox/edit pair
set(h.qsm.iLSQR.checkbox.lambda,	'Callback', {@CheckboxEditPair_Callback,h.qsm.iLSQR.edit.lambda,0});

end