%% h = sepia_handle_panel_qsm_FANSI(hParent,h,position)
%
% Input
% --------------
% hParent       : parent handle of this panel
% h             : global structure contains all handles
% position      : position of this panel
%
% Output
% --------------
% h             : global structure contains all new and other handles
%
% Description: This GUI function creates a panel for FANSI method
%
% Kwok-shing Chan @ DCCN
% k.chan@donders.ru.nl
% Date created: 1 June 2018
% Date last modified: 
%
%
function h = sepia_handle_panel_qsm_FANSI(hParent,h,position)

%% set default values
defaultTol      = 1;
defaultLambda   = 3e-5;
defaultMu       = 5e-5;
defaultMu2      = 1;
defaultMaxIter  = 50;

defaultBeta = 1;
defaultMuh  = 1;
%% layout of the panel
% define maximum level of options and spacing between options
nlevel  = 4; % 4 rows in the panel
ncol    = 3; % 2 columns in the panel
spacing = 0.03;
height  = (1-(nlevel+1)*spacing)/nlevel;
button  = (height+spacing:height+spacing:(height+spacing)*nlevel) - height;
rspacing = 0.01;
width   = (1-(ncol+1)*rspacing)/ncol;
left    = (rspacing:width+rspacing:(width+rspacing)*ncol);

%% Parent handle of CFS panel children

h.qsm.panel.FANSI = uipanel(hParent,...
        'Title','FAst Nonlinear Susceptibility Inversion (FANSI)',...
        'position',position,...
        'backgroundcolor',get(h.fig,'color'),'Visible','off');

%% Children of CFS panel
    
    subwidth(1) = 0.65;
    subwidth(2) = 1-subwidth(1);
    % column 1
    % text|edit field pair: tolerance
    h.qsm.FANSI.text.tol = uicontrol('Parent',h.qsm.panel.FANSI,...
        'Style','text',...
        'String','Tolerance:',...
        'units','normalized','position',[left(1) button(4) width*subwidth(1) height],...
        'HorizontalAlignment','left',...
        'backgroundcolor',get(h.fig,'color'),...
        'tooltip','Convergence limit, change rate in the solution');
    h.qsm.FANSI.edit.tol = uicontrol('Parent',h.qsm.panel.FANSI,...
        'Style','edit',...
        'String',num2str(defaultTol),...
        'units','normalized','position',[left(1)+width*subwidth(1) button(4) width*subwidth(2) height],...
        'backgroundcolor','white');
    
    % text|edit field pair: maximum iterations
    h.qsm.FANSI.text.maxIter = uicontrol('Parent',h.qsm.panel.FANSI,...
        'Style','text',...
        'String','Max. iterations:',...
        'units','normalized','position',[left(1) button(3) width*subwidth(1) height],...
        'HorizontalAlignment','left',...
        'backgroundcolor',get(h.fig,'color'),...
        'tooltip','Maximum iterations allowed');
    h.qsm.FANSI.edit.maxIter = uicontrol('Parent',h.qsm.panel.FANSI,...
        'Style','edit',...
        'String',num2str(defaultMaxIter),...
        'units','normalized','position',[left(1)+width*subwidth(1) button(3) width*subwidth(2) height],...
        'backgroundcolor','white');
    
    % text|popup field pair: solver
    h.qsm.FANSI.text.solver = uicontrol('Parent',h.qsm.panel.FANSI,...
        'Style','text',...
        'String','Solver:',...
        'units','normalized','position',[left(1) button(2) width*subwidth(1) height],...
        'HorizontalAlignment','left',...
        'backgroundcolor',get(h.fig,'color'));
    h.qsm.FANSI.popup.solver = uicontrol('Parent',h.qsm.panel.FANSI,...
        'Style','popup',...
        'String',{'Linear','Non-linear'},...
        'units','normalized','position',[left(1)+width*subwidth(1) button(2) width*subwidth(2) height],...
        'backgroundcolor','white');
    
    % text|popup field pair: constraint
    h.qsm.FANSI.text.constraints = uicontrol('Parent',h.qsm.panel.FANSI,...
        'Style','text',...
        'String','Constraint:',...
        'units','normalized','position',[left(1) button(1) width*subwidth(1) height],...
        'HorizontalAlignment','left',...
        'backgroundcolor',get(h.fig,'color'));
    h.qsm.FANSI.popup.constraints = uicontrol('Parent',h.qsm.panel.FANSI,...
        'Style','popup',...
        'String',{'TV','TGV'},...
        'units','normalized','position',[left(1)+width*subwidth(1) button(1) width*subwidth(2) height],...
        'backgroundcolor','white');
    
    % column 2
    % text|edit field pair: fidelity consistency
    h.qsm.FANSI.text.mu2 = uicontrol('Parent',h.qsm.panel.FANSI,...
        'Style','text',...
        'String','Fidelity consistency:',...
        'units','normalized','position',[left(2) button(4) width*subwidth(1) height],...
        'HorizontalAlignment','left',...
        'backgroundcolor',get(h.fig,'color'));
    h.qsm.FANSI.edit.mu2 = uicontrol('Parent',h.qsm.panel.FANSI,...
        'Style','edit',...
        'String',num2str(defaultMu2),...
        'units','normalized','position',[left(2)+width*subwidth(1) button(4) width*subwidth(2) height],...
        'backgroundcolor','white');
    
    % text|edit field pair: gradient L1 penalty
    h.qsm.FANSI.text.lambda = uicontrol('Parent',h.qsm.panel.FANSI,...
        'Style','text',...
        'String','Gradient L1 penalty:',...
        'units','normalized','position',[left(2) button(3) width*subwidth(1) height],...
        'HorizontalAlignment','left',...
        'backgroundcolor',get(h.fig,'color'),...
        'tooltip','Regularisation rate');
    h.qsm.FANSI.edit.lambda = uicontrol('Parent',h.qsm.panel.FANSI,...
        'Style','edit',...
        'String',num2str(defaultLambda),...
        'units','normalized','position',[left(2)+width*subwidth(1) button(3) width*subwidth(2) height],...
        'backgroundcolor','white');

    % text|edit field pair: gradient consistency
    h.qsm.FANSI.text.mu = uicontrol('Parent',h.qsm.panel.FANSI,...
        'Style','text',...
        'String','Gradient consistency:',...
        'units','normalized','position',[left(2) button(2) width*subwidth(1) height],...
        'HorizontalAlignment','left',...
        'backgroundcolor',get(h.fig,'color'));
    h.qsm.FANSI.edit.mu = uicontrol('Parent',h.qsm.panel.FANSI,...
        'Style','edit',...
        'String',num2str(defaultMu),...
        'units','normalized','position',[left(2)+width*subwidth(1) button(2) width*subwidth(2) height],...
        'backgroundcolor','white');
    
    % text|popup field pair: gradient mode
    h.qsm.FANSI.text.gradientMode = uicontrol('Parent',h.qsm.panel.FANSI,...
        'Style','text',...
        'String','Gradient mode:',...
        'units','normalized','position',[left(2) button(1) width*subwidth(1) height],...
        'HorizontalAlignment','left',...
        'backgroundcolor',get(h.fig,'color'));
    h.qsm.FANSI.popup.gradientMode = uicontrol('Parent',h.qsm.panel.FANSI,...
        'Style','popup',...
        'String',{'Vector field','L1 norm','L2 norm'},...
        'units','normalized','position',[left(2)+width*subwidth(1) button(1) width*subwidth(2) height],...
        'backgroundcolor','white');

    % column 3
    % weak harmonic field 
    h.qsm.FANSI.checkbox.isWeakHarmonic = uicontrol('Parent',h.qsm.panel.FANSI ,...
        'Style','checkbox','String','Weak-Harmonic Regularisation',...
        'units','normalized','Position',[left(3) button(4) width height],...
        'backgroundcolor',get(h.fig,'color'),...
        'tooltip','Weak-harmonic regularization for quantitative susceptibility mapping');
    % text|edit field pair: harmonic constrain weight
    h.qsm.FANSI.text.beta = uicontrol('Parent',h.qsm.panel.FANSI,...
        'Style','text',...
        'String','Harmonic constrain:',...
        'units','normalized','position',[left(3) button(3) width*subwidth(1) height],...
        'HorizontalAlignment','left',...
        'backgroundcolor',get(h.fig,'color'));
    h.qsm.FANSI.edit.beta = uicontrol('Parent',h.qsm.panel.FANSI,...
        'Style','edit',...
        'String',num2str(defaultBeta),...
        'Enable','off',...
        'units','normalized','position',[left(3)+width*subwidth(1) button(3) width*subwidth(2) height],...
        'backgroundcolor','white');
    % text|edit field pair: harmonic consistency weight
    h.qsm.FANSI.text.muh = uicontrol('Parent',h.qsm.panel.FANSI,...
        'Style','text',...
        'String','Harmonic consistency:',...
        'units','normalized','position',[left(3) button(2) width*subwidth(1) height],...
        'HorizontalAlignment','left',...
        'backgroundcolor',get(h.fig,'color'));
    h.qsm.FANSI.edit.muh = uicontrol('Parent',h.qsm.panel.FANSI,...
        'Style','edit',...
        'String',num2str(defaultMuh),...
        'Enable','off',...
        'units','normalized','position',[left(3)+width*subwidth(1) button(2) width*subwidth(2) height],...
        'backgroundcolor','white');


%% set callbacks
set(h.qsm.FANSI.edit.lambda,	'Callback', {@EditInputMinMax_Callback,defaultLambda,   0,0});
set(h.qsm.FANSI.edit.maxIter,	'Callback', {@EditInputMinMax_Callback,defaultMaxIter,  1,1});
set(h.qsm.FANSI.edit.mu,     	'Callback', {@EditInputMinMax_Callback,defaultMu,       0,0});
set(h.qsm.FANSI.edit.mu2,     	'Callback', {@EditInputMinMax_Callback,defaultMu2,      0,0});
set(h.qsm.FANSI.edit.tol,    	'Callback', {@EditInputMinMax_Callback,defaultTol,      0,0});
set(h.qsm.FANSI.edit.beta,     	'Callback', {@EditInputMinMax_Callback,defaultBeta,     0,0});
set(h.qsm.FANSI.edit.muh,     	'Callback', {@EditInputMinMax_Callback,defaultMuh,      0,0});

set(h.qsm.FANSI.checkbox.isWeakHarmonic,	'Callback', {@CheckboxEditPair_Callback,{h.qsm.FANSI.edit.beta,h.qsm.FANSI.edit.muh},1});


end