%% h = sepia_handle_panel_qsm_STIiLSQR(hParent,h,position)
%
% Input
% --------------
% hParent       : parent handle of this panel
% h             : global structure contains all handles
% position      : position of this panel
%
% Output
% --------------
% h             : global structure contains all new and other handles
%
% Description: This GUI function creates a panel for STIiLSQR method
%
% Kwok-shing Chan @ DCCN
% k.chan@donders.ru.nl
% Date created: 1 June 2018
% Date modified: 3 April 2020 (v0.8.0)
%
%
function h = sepia_handle_panel_qsm_STIiLSQR(hParent,h,position)

%% set default values
defaultTol1         = 0.01;
defaultTol2         = 0.001;
defaultPadSize    	= 12;
defaultThreshold	= 0.01;
defaultMaxIter      = 100;

%% Tooltips
% tooltip.qsm.STIiLSQR.threshold	= '';
% tooltip.qsm.STIiLSQR.maxIter      = '';

%% layout of the panel
nrow        = 4;
rspacing    = 0.01;
ncol        = 2;
cspacing    = 0.01;
[height,bottom,width,left] = sepia_layout_measurement(nrow,rspacing,ncol,cspacing);

%% Parent handle of CFS panel children

h.qsm.panel.STIiLSQR = uipanel(hParent,...
    'Title','STI suite iLSQR',...
    'position',position,...
    'backgroundcolor',get(h.fig,'color'),'Visible','off');

%% Children of CFS panel
    
    % width of each element in a functional column, in normalised unit of
    % the functional column width
    subwidth(1) = width*0.5;
    subwidth(2) = width-subwidth(1);
    
    % text|edit field pair: threshold
    h.qsm.STIiLSQR.text.threshold = uicontrol('Parent',h.qsm.panel.STIiLSQR,...
        'Style','text',...
        'String','Threshold:',...
        'units','normalized','position',[left(1) bottom(1) subwidth(1) height],...
        'HorizontalAlignment','left',...
        'backgroundcolor',get(h.fig,'color'));
    h.qsm.STIiLSQR.edit.threshold = uicontrol('Parent',h.qsm.panel.STIiLSQR,...
        'Style','edit',...
        'String',num2str(defaultThreshold),...
        'units','normalized','position',[left(1)+subwidth(1) bottom(1) subwidth(2) height],...
        'backgroundcolor','white');

	% text|edit field pair: maximum iterations
    h.qsm.STIiLSQR.text.maxIter = uicontrol('Parent',h.qsm.panel.STIiLSQR,...
        'Style','text',...
        'String','Max. iterations:',...
        'units','normalized','position',[left(1) bottom(2) subwidth(1) height],...
        'HorizontalAlignment','left',...
        'backgroundcolor',get(h.fig,'color'));
    h.qsm.STIiLSQR.edit.maxIter = uicontrol('Parent',h.qsm.panel.STIiLSQR,...
        'Style','edit',...
        'String',num2str(defaultMaxIter),...
        'units','normalized','position',[left(1)+subwidth(1) bottom(2) subwidth(2) height],...
        'backgroundcolor','white');

	% text|edit field pair: tolerance 1
    h.qsm.STIiLSQR.text.tol1 = uicontrol('Parent',h.qsm.panel.STIiLSQR,...
        'Style','text',...
        'String','Tolerance 1:',...
        'units','normalized','position',[left(1) bottom(3) subwidth(1) height],...
        'HorizontalAlignment','left',...
        'backgroundcolor',get(h.fig,'color'));
    h.qsm.STIiLSQR.edit.tol1 = uicontrol('Parent',h.qsm.panel.STIiLSQR,...
        'Style','edit',...
        'String',num2str(defaultTol1),...
        'units','normalized','position',[left(1)+subwidth(1) bottom(3) subwidth(2) height],...
        'backgroundcolor','white');

    % text|edit field pair: tolerance 2
    h.qsm.STIiLSQR.text.tol2 = uicontrol('Parent',h.qsm.panel.STIiLSQR,...
        'Style','text',...
        'String','Tolerance 2:',...
        'units','normalized','position',[left(1) bottom(4) subwidth(1) height],...
        'HorizontalAlignment','left',...
        'backgroundcolor',get(h.fig,'color'));
    h.qsm.STIiLSQR.edit.tol2 = uicontrol('Parent',h.qsm.panel.STIiLSQR,...
        'Style','edit',...
        'String',num2str(defaultTol2),...
        'units','normalized','position',[left(1)+subwidth(1) bottom(4) subwidth(2) height],...
        'backgroundcolor','white');

    % text|edit field pair: pad size
    h.qsm.STIiLSQR.text.padSize = uicontrol('Parent',h.qsm.panel.STIiLSQR,...
        'Style','text',...
        'String','Pad size:',...
        'units','normalized','position',[left(2) bottom(1) subwidth(1) height],...
        'HorizontalAlignment','left',...
        'backgroundcolor',get(h.fig,'color'));
    h.qsm.STIiLSQR.edit.padSize = uicontrol('Parent',h.qsm.panel.STIiLSQR,...
        'Style','edit',...
        'String',num2str(defaultPadSize),...
        'units','normalized','position',[left(2)+subwidth(1) bottom(1) subwidth(2) height],...
        'backgroundcolor','white');

%% set callbacks
set(h.qsm.STIiLSQR.edit.maxIter,	'Callback', {@EditInputMinMax_Callback,defaultMaxIter,  1,1});
set(h.qsm.STIiLSQR.edit.padSize, 	'Callback', {@EditInputMinMax_Callback,defaultPadSize,  1,0});
set(h.qsm.STIiLSQR.edit.threshold,	'Callback', {@EditInputMinMax_Callback,defaultThreshold,0,0});
set(h.qsm.STIiLSQR.edit.tol1,     	'Callback', {@EditInputMinMax_Callback,defaultTol1,     0,0});
set(h.qsm.STIiLSQR.edit.tol2,    	'Callback', {@EditInputMinMax_Callback,defaultTol2,     0,0});

end