%% h = sepia_handle_panel_qsm_FANSI(hParent,h,position)
%
% Input
% --------------
% hParent       : parent handle of this panel
% h             : global structure contains all handles
% position      : position of this panel
%
% Output
% --------------
% h             : global structure contains all new and other handles
%
% Description: This GUI function creates a panel for SWI method
%
% Kwok-shing Chan @ DCCN
% k.chan@donders.ru.nl
% Date created: 1 June 2018
% Date last modified: 
%
%
function h = sepia_handle_panel_swi_SWI(hParent,h,position)

%% set default values
defaultM            = 4;
defaultthreshold    = 'pi';
defaultFilterSize   = 12;
defaultmIP          = 4;

%% Parent handle of panel children

h.swi.panel.SWI = uipanel(hParent,...
        'Title','SWI',...
        'position',position,...
        'backgroundcolor',get(h.fig,'color'),'Visible','on');

%% Children of panel

    % text|edit field pair: radius
    h.swi.SWI.text.m = uicontrol('Parent',h.swi.panel.SWI,'Style','text',...
        'String','Contrast:',...
        'units','normalized','position',[0.01 0.75 0.2 0.2],...
        'HorizontalAlignment','left',...
        'backgroundcolor',get(h.fig,'color'),...
        'tooltip','Radius of spherical mean kernel');
    h.swi.SWI.edit.m = uicontrol('Parent',h.swi.panel.SWI,'Style','edit',...
        'String',num2str(defaultM),...
        'units','normalized','position',[0.25 0.75 0.2 0.2],...0
        'backgroundcolor','white');

    % text|edit field pair: threshold
    h.swi.SWI.text.threshold = uicontrol('Parent',h.swi.panel.SWI,'Style','text',...
        'String','Threshold (rad):',...
        'units','normalized','position',[0.01 0.5 0.2 0.2],...
        'HorizontalAlignment','left',...
        'backgroundcolor',get(h.fig,'color'),...
        'tooltip','Threshold used in truncated SVD');
    h.swi.SWI.edit.threshold = uicontrol('Parent',h.swi.panel.SWI,'Style','edit',...
        'String',defaultthreshold,...
        'units','normalized','position',[0.25 0.5 0.2 0.2],...
        'backgroundcolor','white');
    
    % text|edit field pair: filter size
    h.swi.SWI.text.filterSize = uicontrol('Parent',h.swi.panel.SWI,'Style','text',...
        'String','Filter size:',...
        'units','normalized','position',[0.01 0.25 0.2 0.2],...
        'HorizontalAlignment','left',...
        'backgroundcolor',get(h.fig,'color'),...
        'tooltip','Threshold used in truncated SVD');
    h.swi.SWI.edit.filterSize = uicontrol('Parent',h.swi.panel.SWI,'Style','edit',...
        'String',num2str(defaultFilterSize),...
        'units','normalized','position',[0.25 0.25 0.2 0.2],...
        'backgroundcolor','white');
    
    % text|popup field pair: method
    h.swi.SWI.text.method = uicontrol('Parent',h.swi.panel.SWI,...
        'Style','text',...
        'String','Method:',...
        'units','normalized','position',[0.01 0.01 0.2 0.2],...
        'HorizontalAlignment','left',...
        'backgroundcolor',get(h.fig,'color'));
    h.swi.SWI.popup.method = uicontrol('Parent',h.swi.panel.SWI,...
        'Style','popup',...
        'String',{'default','multi-echo'},...
        'units','normalized','position',[0.25 0.01 0.2 0.2],...
        'backgroundcolor','white');
    
    % checkbox: save positive phase image
    h.swi.SWI.checkbox.positive = uicontrol('Parent',h.swi.panel.SWI,'Style','checkbox',...
        'String','Save positive phase weighted images',...
        'units','normalized','position',[0.5 0.75 0.4 0.2],...
        'HorizontalAlignment','left',...
        'backgroundcolor',get(h.fig,'color'),'Value',true');
    % checkbox: save nagative phase image
    h.swi.SWI.checkbox.negative = uicontrol('Parent',h.swi.panel.SWI,'Style','checkbox',...
        'String','Save negative phase weighted images',...
        'units','normalized','position',[0.5 0.5 0.4 0.2],...
        'HorizontalAlignment','left',...
        'backgroundcolor',get(h.fig,'color'));
    % checkbox: save nagative phase image
    h.swi.SWI.checkbox.mIP = uicontrol('Parent',h.swi.panel.SWI,'Style','checkbox',...
        'String','Save mIP image, #slices',...
        'units','normalized','position',[0.5 0.25 0.25 0.2],...
        'HorizontalAlignment','left',...
        'backgroundcolor',get(h.fig,'color'),'Value',true);
    h.swi.SWI.edit.mIP = uicontrol('Parent',h.swi.panel.SWI,'Style','edit',...
        'String',num2str(defaultmIP),...
        'units','normalized','position',[0.8 0.25 0.15 0.2],...
        'backgroundcolor','white','enable','on');

%% set callbacks
set(h.swi.SWI.edit.m,           'Callback', {@EditInputMinMax_Callback,defaultM,   1,0});
set(h.swi.SWI.edit.threshold,	'Callback', {@EditInputMinMax_Callback,str2double(defaultthreshold),  0,0});
set(h.swi.SWI.edit.filterSize,  'Callback', {@EditInputMinMax_Callback,defaultFilterSize,       1,1});
set(h.swi.SWI.checkbox.mIP,     'Callback', {@CheckboxEditPair_Callback,h.swi.SWI.edit.mIP,1});
end