%% h = sepia_handle_panel_bkgRemoval_SHARP(hParent,h,position)
%
% Input
% --------------
% hParent       : parent handle of this panel
% h             : global structure contains all handles
% position      : position of this panel
%
% Output
% --------------
% h             : global structure contains all new and other handles
%
% Description: This GUI function creates a panel for LBV method
%
% Kwok-shing Chan @ DCCN
% k.chan@donders.ru.nl
% Date created: 1 June 2018
% Date last modified: 
%
%
function h = sepia_handle_panel_swi_SMWI(hParent,h,position)

%% set default values
defaultM            = 4;
defaultthreshold    = 1;
defaultmIP          = 4;

%% Parent handle of SMWI panel children

h.swi.panel.SMWI = uipanel(hParent,...
    'Title','SMWI',...
    'position',position,...
    'backgroundcolor',get(h.fig,'color'),'Visible','off');
    
%% children of SMWI panel

    % text|edit field pair: radius
    h.swi.SMWI.text.m = uicontrol('Parent',h.swi.panel.SMWI,'Style','text',...
        'String','Contrast:',...
        'units','normalized','position',[0.01 0.75 0.2 0.2],...
        'HorizontalAlignment','left',...
        'backgroundcolor',get(h.fig,'color'),...
        'tooltip','Radius of spherical mean kernel');
    h.swi.SMWI.edit.m = uicontrol('Parent',h.swi.panel.SMWI,'Style','edit',...
        'String',num2str(defaultM),...
        'units','normalized','position',[0.25 0.75 0.2 0.2],...
        'backgroundcolor','white');

    % text|edit field pair: threshold
    h.swi.SMWI.text.threshold = uicontrol('Parent',h.swi.panel.SMWI,'Style','text',...
        'String','Threshold (ppm):',...
        'units','normalized','position',[0.01 0.5 0.2 0.2],...
        'HorizontalAlignment','left',...
        'backgroundcolor',get(h.fig,'color'),...
        'tooltip','Threshold used in truncated SVD');
    h.swi.SMWI.edit.threshold = uicontrol('Parent',h.swi.panel.SMWI,'Style','edit',...
        'String',num2str(defaultthreshold),...
        'units','normalized','position',[0.25 0.5 0.2 0.2],...
        'backgroundcolor','white');
    
    % checkbox: save paramagetic image
    h.swi.SMWI.checkbox.paramagnetic = uicontrol('Parent',h.swi.panel.SMWI,'Style','checkbox',...
        'String','Save paramagnetic weighted images',...
        'units','normalized','position',[0.5 0.75 0.4 0.2],...
        'HorizontalAlignment','left',...
        'backgroundcolor',get(h.fig,'color'),'Value',true');
    % checkbox: save diamagetic image
    h.swi.SMWI.checkbox.diamagnetic = uicontrol('Parent',h.swi.panel.SMWI,'Style','checkbox',...
        'String','Save diamagnetic weighted images',...
        'units','normalized','position',[0.5 0.5 0.4 0.2],...
        'HorizontalAlignment','left',...
        'backgroundcolor',get(h.fig,'color'));
    
    % checkbox: save nagative phase image
    h.swi.SMWI.checkbox.mIP = uicontrol('Parent',h.swi.panel.SMWI,'Style','checkbox',...
        'String','Save mIP image, #slices',...
        'units','normalized','position',[0.5 0.25 0.25 0.2],...
        'HorizontalAlignment','left',...
        'backgroundcolor',get(h.fig,'color'),'Value',true);
    h.swi.SMWI.edit.mIP = uicontrol('Parent',h.swi.panel.SMWI,'Style','edit',...
        'String',num2str(defaultmIP),...
        'units','normalized','position',[0.8 0.25 0.15 0.2],...
        'backgroundcolor','white','enable','on');

%% set callbacks
set(h.swi.SMWI.edit.m,          'Callback', {@EditInputMinMax_Callback,defaultM,     	1,0});
set(h.swi.SMWI.edit.threshold,	'Callback', {@EditInputMinMax_Callback,defaultthreshold,0,0});
set(h.swi.SMWI.checkbox.mIP,    'Callback', {@CheckboxEditPair_Callback,h.swi.SMWI.edit.mIP,1});
end