%% get_set_clearswi(h,mode,input)
%
% Input
% --------------
% h             : structure contains all handles of SEPIA
% mode          : 'set' - extract information from GUI to config file
%                 'get' - extract information from config file to GUI
% input         : if mode is 'set' then input should be fid
%                 if mode is 'get' then input should be confige file text
%
% Description: Information communication between config file and GUI
%
% Korbinian Eckstein @ UQ
% korbinian90@gmail.com
% Date created: 26 September 2022
% Date modified:
%
%
function get_set_clearswi(h,mode,input)

str_pattern = {'.swismwi.phaseScalingType',...
               '.swismwi.phaseScalingStrength',...
               '.swismwi.filterSize',...
               '.swismwi.unwrappingAlgorithm',...
               '.swismwi.echoCombineMethod',...
               '.swismwi.echoCombineMethodAdd',...
               '.swismwi.echoes',...
               '.swismwi.softplusScaling',...
               '.swismwi.sensitivityCorrection',...
               '.swismwi.ismIP',...
               '.swismwi.slice_mIP',...
               };

action_handle = {h.swismwi.clearswi.popup.phaseScalingType,...
                 h.swismwi.clearswi.edit.phaseScalingStrength,...
                 h.swismwi.clearswi.edit.filterSize,...
                 h.swismwi.clearswi.popup.unwrappingAlgorithm,...
                 h.swismwi.clearswi.popup.echoCombineMethod,...
                 h.swismwi.clearswi.edit.echoCombineMethodAdd,...
                 h.swismwi.clearswi.edit.echoes...
                 h.swismwi.clearswi.checkbox.softplusScaling,...
                 h.swismwi.clearswi.checkbox.sensitivityCorrection,...
                 h.swismwi.clearswi.checkbox.mIP,...
                 h.swismwi.clearswi.edit.mIP,...
                 };

switch lower(mode)
    case 'set'
        fid = input;
        
        % Number
        for k = [2 6 11]
            fprintf(fid,'algorParam%s = %s ;\n'         ,str_pattern{k},get(action_handle{k},	'String'));
        end
        % String
        for k = [3 7]
            fprintf(fid,'algorParam%s = ''%s'' ;\n'         ,str_pattern{k},get(action_handle{k},	'String'));
        end
        % Checkbox
        for k = [8 9 10]
            fprintf(fid,'algorParam%s = %i ;\n'         ,str_pattern{k},get(action_handle{k},	'Value'));
        end
        % Popup
        for k = [1 4 5]
            fprintf(fid,'algorParam%s = ''%s'' ;\n'     ,str_pattern{k},action_handle{k}.String{action_handle{k}.Value,1});
        end

end