%% h = sepia_handle_panel_bkgRemoval_LBV(hParent,h,position)
%
% Input
% --------------
% hParent       : parent handle of this panel
% h             : global structure contains all handles
% position      : position of this panel
%
% Output
% --------------
% h             : global structure contains all new and other handles
%
% Description: This GUI function creates a panel for LBV method
%
% Kwok-shing Chan @ DCCN
% k.chan@donders.ru.nl
% Date created: 1 June 2018
% Date modified: 3 April 2020 (v0.8.0)
%
%
function h = sepia_handle_panel_bkgRemoval_LBV(hParent,h,position)

%% set default values
defaultTol      = 0.0001;
defaultDepth    = 5;
defaultpeel     = 2;

%% Tooltips
tooltip.bkgRemoval.LBV.tol      = 'Iteration stopping criteria on the coarsest grid';
tooltip.bkgRemoval.LBV.depth  	= 'Multigrid level: no. of length scales. The largest length scale is 2^depth * voxel size';
tooltip.bkgRemoval.LBV.peel     = 'No. of boundary layers to be peeled off (i.e. disgarded)';

%% layout of the panel
nrow        = 4;
rspacing    = 0.01;
ncol        = 2;
cspacing    = 0.01;
[height,bottom,width,left] = sepia_layout_measurement(nrow,rspacing,ncol,cspacing);

%% Parent handle of LBV panel children

h.bkgRemoval.panel.LBV = uipanel(hParent,...
    'Title','Laplacian boundary value (LBV)',...
    'position',position,...
    'backgroundcolor',get(h.fig,'color'));

%% Children of LBV panel

    % width of each element in a functional column, in normalised unit of
    % the functional column width
    subwidth(1) = width*0.5;
    subwidth(2) = width-subwidth(1);
    
    % row 1
    % functional col: text|edit field pair: tolerance
    h.bkgRemoval.LBV.text.tol = uicontrol('Parent',h.bkgRemoval.panel.LBV ,...
        'Style','text',...
        'String','Tolerance:',...
        'units','normalized','position',[left(1) bottom(1) subwidth(1) height],...
        'HorizontalAlignment','left',...
        'backgroundcolor',get(h.fig,'color'),...
        'tooltip',tooltip.bkgRemoval.LBV.tol);
    h.bkgRemoval.LBV.edit.tol = uicontrol('Parent',h.bkgRemoval.panel.LBV ,...
        'Style','edit',...
        'String',num2str(defaultTol),...
        'units','normalized','position',[left(1)+subwidth(1) bottom(1) subwidth(2) height],...
        'backgroundcolor','white');
    
    % row 2
    % functional col: text|edit field pair: depth
    h.bkgRemoval.LBV.text.depth = uicontrol('Parent',h.bkgRemoval.panel.LBV ,...
        'Style','text',...
        'String','Depth:',...
        'units','normalized','position',[left(1) bottom(2) subwidth(1) height],...
        'HorizontalAlignment','left',...
        'backgroundcolor',get(h.fig,'color'),...
        'tooltip',tooltip.bkgRemoval.LBV.depth);
    h.bkgRemoval.LBV.edit.depth = uicontrol('Parent',h.bkgRemoval.panel.LBV ,...
        'Style','edit',...
        'String',num2str(defaultDepth),...
        'units','normalized','position',[left(1)+subwidth(1) bottom(2) subwidth(2) height],...
        'backgroundcolor','white');
    
    % row 3
    % functional col: text|edit field pair: peel
    h.bkgRemoval.LBV.text.peel = uicontrol('Parent',h.bkgRemoval.panel.LBV ,...
        'Style','text',...
        'String','Peel:',...
        'units','normalized','position',[left(1) bottom(3) subwidth(1) height],...
        'HorizontalAlignment','left',...
        'backgroundcolor',get(h.fig,'color'),...
        'tooltip',tooltip.bkgRemoval.LBV.peel);
    h.bkgRemoval.LBV.edit.peel = uicontrol('Parent',h.bkgRemoval.panel.LBV ,...
        'Style','edit',...
        'String',num2str(defaultpeel),...
        'units','normalized','position',[left(1)+subwidth(1) bottom(3) subwidth(2) height],...
        'backgroundcolor','white');

%% Set callbacks
set(h.bkgRemoval.LBV.edit.depth,    'Callback', {@EditInputMinMax_Callback,defaultDepth ,1,-1});
set(h.bkgRemoval.LBV.edit.peel,     'Callback', {@EditInputMinMax_Callback,defaultpeel  ,1,0});
set(h.bkgRemoval.LBV.edit.tol,      'Callback', {@EditInputMinMax_Callback,defaultTol   ,0,0});

end