%% h = sepia_handle_panel_dataIO(hParent,h,position)
%
% Input
% --------------
% hParent       : parent handle of this panel
% hFig          : handle of the GUI
% h             : global structure contains all handles
% position      : position of this panel
%
% Output
% --------------
% h             : global structure contains all new and other handles
%
% Description: This GUI function creates a panel for I/O control
%
% Kwok-Shing Chan @ DCCN
% k.chan@donders.ru.nl
% Date created: 16 April 2018
% Date modified: 30 May 2018
% Date modified: 5 March 2020 (v0.8.0)
%
%
function h = sepia_handle_panel_dataIO(hParent,h,position)

% default value
defaultFractionalThres  = 0.5;
defaultGradientThres    = 0; 

% define maximum level of options and spacing between options
nlevel  = 5; % 5 rows in the panel
ncol    = 2; % 2 columns in the panel
spacing = 0.02;
height  = (1-(nlevel+1)*spacing)/nlevel;
button  = (height+spacing:height+spacing:(height+spacing)*nlevel) - height;
rspacing = 0.01;
width   = (1-(ncol+1)*rspacing)/ncol;
left    = (rspacing:width+rspacing:(width+rspacing)*ncol);

% Parent of dataIO panel
h.StepsPanel.dataIO = uipanel(hParent,'Title','I/O',...
    'Position',[position(1) position(2) 0.95 0.2],...
    'fontweight', 'bold',...
    'backgroundcolor',get(h.fig,'color'));

    % input directory
    col_width = [0.15, 0.26, 0.06];
    h.dataIO.text.input = uicontrol(h.StepsPanel.dataIO,...
        'Style','text','String','Input directory:',...
        'Units','normalized','Position', [left(1) button(5) col_width(1) height],...
        'HorizontalAlignment','left',...
        'backgroundcolor',get(h.fig,'color'),...
        'tooltip','Directory contains all essential files (*ph*.nii*, *mag*.nii* and *header*.mat)');
    h.dataIO.edit.input = uicontrol('Parent',h.StepsPanel.dataIO,...
        'Style','edit',...
        'units','normalized','position',[left(1)+col_width(1) button(5) col_width(2) height],...
        'HorizontalAlignment','left',...
        'backgroundcolor','white');
    h.dataIO.button.input = uicontrol('Parent',h.StepsPanel.dataIO,...
        'Style','pushbutton','String','open',...
        'units','normalized','position',[left(1)+sum(col_width(1:2)) button(5) col_width(3) height],...
        'backgroundcolor','white');
    
    % output basename
    h.dataIO.text.output = uicontrol('Parent',h.StepsPanel.dataIO,...
        'Style','text','String','Output prefix:',...
        'units','normalized','Position',[left(2) button(5) col_width(1) height],...
        'HorizontalAlignment','left',...
        'backgroundcolor',get(h.fig,'color'),...
        'tooltip','Output directory with filename prefix. Default output prefix is ''/input_dir/output/sepia''');
    h.dataIO.edit.output = uicontrol('Parent',h.StepsPanel.dataIO,...
        'Style','edit',...
        'units','normalized','position',[left(2)+col_width(1) button(5) col_width(2) height],...
        'HorizontalAlignment','left',...
        'backgroundcolor','white');
    h.dataIO.button.output = uicontrol('Parent',h.StepsPanel.dataIO,...
        'Style','pushbutton','String','open',...
        'units','normalized','position',[left(2)+sum(col_width(1:2)) button(5) col_width(3) height],...
        'backgroundcolor','white');
    
    % brain mask
    h.dataIO.text.maskdir = uicontrol('Parent',h.StepsPanel.dataIO,...
        'Style','text','String','Brain mask:',...
        'units','normalized','Position',[left(2) button(4) col_width(1) height],...
        'HorizontalAlignment','left',...
        'backgroundcolor',get(h.fig,'color'),...
        'tooltip','Specify a NIfTI mask file (.nii/.nii.gz). If the input directory contains a NIfTI file with string *mask* in the filename then it will be read automatically');
    h.dataIO.edit.maskdir = uicontrol('Parent',h.StepsPanel.dataIO,...
        'Style','edit',...
        'units','normalized','position',[left(2)+col_width(1) button(4) col_width(2) height],...
        'HorizontalAlignment','left',...
        'backgroundcolor','white');
    h.dataIO.button.maskdir = uicontrol('Parent',h.StepsPanel.dataIO,...
        'Style','pushbutton','String','open',...
        'units','normalized','position',[left(2)+sum(col_width(1:2)) button(4) col_width(3) height],...
        'backgroundcolor','white');
    
    % input data1
    h.dataIO.text.inputData1 = uicontrol(h.StepsPanel.dataIO,...
        'Style','text','String','or Phase:',...
        'Units','normalized','Position', [left(1) button(4) col_width(1) height],...
        'HorizontalAlignment','left',...
        'backgroundcolor',get(h.fig,'color'),...
        'tooltip','Specify a NIfTI phase image (.nii/.nii.gz)');
    h.dataIO.edit.inputData1 = uicontrol('Parent',h.StepsPanel.dataIO,...
        'Style','edit',...
        'units','normalized','position',[left(1)+col_width(1) button(4) col_width(2) height],...
        'HorizontalAlignment','left',...
        'backgroundcolor','white');
    h.dataIO.button.inputData1 = uicontrol('Parent',h.StepsPanel.dataIO,...
        'Style','pushbutton','String','open',...
        'units','normalized','position',[left(1)+sum(col_width(1:2)) button(4) col_width(3) height],...
        'backgroundcolor','white');
    
    % input data2
    h.dataIO.text.inputData2 = uicontrol(h.StepsPanel.dataIO,...
        'Style','text','String','    Magnitude:',...
        'Units','normalized','Position', [left(1) button(3) col_width(1) height],...
        'HorizontalAlignment','left',...
        'backgroundcolor',get(h.fig,'color'),...
        'tooltip','Specify a NIfTI magnitude image (.nii/.nii.gz)');
    h.dataIO.edit.inputData2 = uicontrol('Parent',h.StepsPanel.dataIO,...
        'Style','edit',...
        'units','normalized','position',[left(1)+col_width(1) button(3) col_width(2) height],...
        'HorizontalAlignment','left',...
        'backgroundcolor','white');
    h.dataIO.button.inputData2 = uicontrol('Parent',h.StepsPanel.dataIO,...
        'Style','pushbutton','String','open',...
        'units','normalized','position',[left(1)+sum(col_width(1:2)) button(3) col_width(3) height],...
        'backgroundcolor','white');
    
    % input data3
    h.dataIO.text.inputData3 = uicontrol(h.StepsPanel.dataIO,...
        'Style','text','String','    Weights:',...
        'Units','normalized','Position', [left(1) button(2) col_width(1) height],...
        'HorizontalAlignment','left',...
        'backgroundcolor',get(h.fig,'color'),...
        'tooltip','Specify a NIfTI weight map for QSM algorithm (.nii/.nii.gz)');
    h.dataIO.edit.inputData3 = uicontrol('Parent',h.StepsPanel.dataIO,...
        'Style','edit',...
        'units','normalized','position',[left(1)+col_width(1) button(2) col_width(2) height],...
        'HorizontalAlignment','left',...
        'backgroundcolor','white',...
        'Enable','on');
    h.dataIO.button.inputData3 = uicontrol('Parent',h.StepsPanel.dataIO,...
        'Style','pushbutton','String','open',...
        'units','normalized','position',[left(1)+sum(col_width(1:2)) button(2) col_width(3) height],...
        'backgroundcolor','white',...
        'Enable','on');
    
    % input header
    h.dataIO.text.inputHeader = uicontrol(h.StepsPanel.dataIO,...
        'Style','text','String','    SEPIA header:',...
        'Units','normalized','Position', [left(1) button(1) col_width(1) height],...
        'HorizontalAlignment','left',...
        'backgroundcolor',get(h.fig,'color'),...
        'tooltip','Specify a SEPIA header');
    h.dataIO.edit.inputHeader = uicontrol('Parent',h.StepsPanel.dataIO,...
        'Style','edit',...
        'units','normalized','position',[left(1)+col_width(1) button(1) col_width(2) height],...
        'HorizontalAlignment','left',...
        'backgroundcolor','white');
    h.dataIO.button.inputHeader = uicontrol('Parent',h.StepsPanel.dataIO,...
        'Style','pushbutton','String','open',...
        'units','normalized','position',[left(1)+sum(col_width(1:2)) button(1) col_width(3) height],...
        'backgroundcolor','white');

    % invert pahse
    h.dataIO.checkbox.invertPhase = uicontrol('Parent',h.StepsPanel.dataIO,...
        'Style','checkbox','String','Invert phase data',...
        'units','normalized','Position',[left(2) button(2) 0.3 height],...
        'backgroundcolor',get(h.fig,'color'),...
        'tooltip','Reverse the direction of frequency shift. This will invert the contrast of the output.');

    % brain extraction
    h.dataIO.checkbox.brainExtraction = uicontrol('Parent',h.StepsPanel.dataIO,...
        'Style','checkbox','String','FSL brain extraction (bet)',...
        'units','normalized','Position',[left(2) button(1) 0.25 height],...
        'backgroundcolor',get(h.fig,'color'),...
        'tooltip','Use FSL bet for brain extraction');
    h.dataIO.text.fractionalThres = uicontrol(h.StepsPanel.dataIO,...
        'Style','text','String','-f',...
        'Units','normalized','Position', [left(2)+0.25 button(1) 0.03 height],...
        'HorizontalAlignment','left',...
        'backgroundcolor',get(h.fig,'color'),...
        'tooltip','Fractional intensity threshold (0->1); default=0.5; smaller values give larger brain outline estimates');
    h.dataIO.edit.fractionalThres = uicontrol('Parent',h.StepsPanel.dataIO,...
        'Style','edit',...
        'units','normalized','position',[left(2)+0.29 button(1) 0.05 height],...
        'HorizontalAlignment','left',...
        'String', num2str(defaultFractionalThres),...
        'Enable','off',...
        'backgroundcolor','white');
    h.dataIO.text.gradientThres = uicontrol(h.StepsPanel.dataIO,...
        'Style','text','String','-g',...
        'Units','normalized','Position', [left(2)+0.35 button(1) 0.03 height],...
        'HorizontalAlignment','left',...
        'backgroundcolor',get(h.fig,'color'),...
        'tooltip','Vertical gradient in fractional intensity threshold (-1->1); default=0; positive values give larger brain outline at bottom, smaller at top');
    h.dataIO.edit.gradientThres = uicontrol('Parent',h.StepsPanel.dataIO,...
        'Style','edit',...
        'units','normalized','position',[left(2)+0.39 button(1) 0.05 height],...
        'HorizontalAlignment','left',...
        'String', num2str(defaultGradientThres),...
        'Enable','off',...
        'backgroundcolor','white');


%% set callback function
% checkbox/edit pair
set(h.dataIO.checkbox.brainExtraction,  'Callback', {@CheckboxBrainExtraction_Callback,h});
% open/edit pari
set(h.dataIO.button.input,           	'Callback', {@ButtonOpen_Callback,h,'input'});
set(h.dataIO.button.output,         	'Callback', {@ButtonOpen_Callback,h,'output'});
set(h.dataIO.button.maskdir,          	'Callback', {@ButtonOpen_Callback,h,'mask'});
set(h.dataIO.button.inputData1,         'Callback', {@ButtonOpen_Callback,h,'inputdata1'});
set(h.dataIO.button.inputData2,         'Callback', {@ButtonOpen_Callback,h,'inputdata2'});
set(h.dataIO.button.inputData3,         'Callback', {@ButtonOpen_Callback,h,'inputdata3'});
set(h.dataIO.button.inputHeader,        'Callback', {@ButtonOpen_Callback,h,'header'});

set(h.dataIO.edit.fractionalThres,    	'Callback', {@EditInputMinMax_Callback,defaultFractionalThres,0,0,1});
set(h.dataIO.edit.gradientThres,        'Callback', {@EditInputMinMax_Callback,defaultGradientThres,0,-1,1});
    
end