%% sepia_configuration_unwrap
%
% Description: a script contains all the spatial phase unwrapping method names and related function names
%
% Kwok-shing Chan @ DCCN
% k.chan@donders.ru.nl
% Date created: 11 March 2020
% Date modified: 28 June 2020
%
% DO NOT change the variable name
% DO NOT change the order of the entities, add a new one at the end instead
% The order of the methods MUST be consistent across all variables
%
%% Phase unwrapping available in SEPIA (MUST)
% Specify the names of the methods
methodUnwrapName        = {'Laplacian (MEDI)',...
                           'Laplacian (STI suite)',...
                           '3D best path',...
                           'Region growing (MEDI)',...
                           'Graphcut',...
                           };
                       % in future, add panel of new method here

%% Wrapper to access algorithms (MUST)
% Specify the name of the wrapper function to connect SEPIA and the
% algorithm
wrapper_Unwrap_function	= {'Wrapper_Unwrap_LaplacianMEDI',...
                           'Wrapper_Unwrap_LaplacianSTI',...
                           'Wrapper_Unwrap_3DBestPath',...
                           'Wrapper_Unwrap_RegionGrowing',...
                           'Wrapper_Unwrap_Graphcut',...
                           } ;
                       % in future, add panel of new method here

%% Enabling unreliable voxel exlusion (MUST)
% Specify if the exclusion of unreliable voxels option in the GUI is
% enabled. The method must return the ture phase value if it is enabled.
% Enable: 'on'
% Disable: 'off'
gui_unwrap_exclusion    = {'off',...
                           'off',...
                           'on',...
                           'on',...
                           'on',...
                           } ;
                       % in future, add panel of new method here