%% sepia_configuration_BFR
%
% Description: a script contains all the background field removal method names and related function names
%
% Kwok-shing Chan @ DCCN
% k.chan@donders.ru.nl
% Date created: 11 March 2020
% Date modified: 
%
% DO NOT change the variable name
% DO NOT change the order of the entities, add a new one at the end instead
% The order of the methods MUST be consistent across all variables
%
%% Background field removal method available in SEPIA (MUST)
% Specify the names of the methods
methodBFRName           = {'LBV',...
                           'PDF',...
                           'RESHARP',...
                           'SHARP',...
                           'VSHARP (STI suite)',...
                           'VSHARP',...
                           'iHARPERELLA',...
                           };
                       % in future, add panel of new method here

%% Wrapper to access BFR algorithms (MUST)
% Specify the name of the wrapper function to connect SEPIA and the
% algorithm
wrapper_BFR_function    = {'Wrapper_BFR_LBV',...
                           'Wrapper_BFR_PDF',...
                           'Wrapper_BFR_RESHARP',...
                           'Wrapper_BFR_SHARP',...
                           'Wrapper_BFR_VSHARPSTI',...
                           'Wrapper_BFR_VSHARP',...
                           'Wrapper_BFR_iHARPERELLA',...
                           } ;
                       % in future, add panel of new method here

%% function that create the method specific panel (Optional, for GUI)
% Specify the name of the function of the panel design 
function_BFR_method_panel = {'sepia_handle_panel_bkgRemoval_LBV',...
                             'sepia_handle_panel_bkgRemoval_PDF',...
                             'sepia_handle_panel_bkgRemoval_RESHARP',...
                             'sepia_handle_panel_bkgRemoval_SHARP',...
                             'sepia_handle_panel_bkgRemoval_VSHARPSTI',...
                             'sepia_handle_panel_bkgRemoval_VSHARP',...
                             'sepia_handle_panel_bkgRemoval_iHARPERELLA'
                             };
                             % in future, add panel of new method here
                             
%% functions that generate and read BFR algorithm parameters (Optional, for GUI)
% Specify the name of the function that export/import parameters to/from
% output config file
config_BFR_function     = {'get_set_bfr_lbv',...
                           'get_set_bfr_pdf',...
                           'get_set_bfr_resharp',...
                           'get_set_bfr_sharp',...
                           'get_set_bfr_vsharpsti',...
                           'get_set_bfr_vsharp',...
                           'get_set_bfr_iharperella',...
                           };
                       % in future, add panel of new method here
