%% sepia_configuration_R2s
%
% Description: a script contains all the background field removal method names and related function names
%
% Kwok-shing Chan @ DCCN
% k.chan@donders.ru.nl
% Date created: 11 March 2020
% Date modified: 
%
% DO NOT change the variable name
% DO NOT change the order of the entities, add a new one at the end instead
% The order of the methods MUST be consistent across all variables
%
%% Background field removal method available in SEPIA (MUST)
% Specify the names of the methods
methodR2sName           = {'Trapezoidal',...
                           'ARLO',...
                           'Geometric sum',...
                           'Sequence of product',...
                           'Linear regression',...
                           'Non-linear least square'};
                       % in future, add panel of new method here

%% Wrapper to access BFR algorithms (MUST)
% Specify the name of the wrapper function to connect SEPIA and the
% algorithm
wrapper_R2s_function    = {'Wrapper_R2s_Trapezoidal',...
                           'Wrapper_R2s_ARLO',...
                           'Wrapper_R2s_GeometricSum',...
                           'Wrapper_R2s_SequenceOfProduct',...
                           'Wrapper_R2s_LinearRegression',...
                           'Wrapper_R2s_NLLS',...
                           } ;
                       % in future, add panel of new method here

%% function that create the method specific panel (Optional, for GUI)
% Specify the name of the function of the panel design 
function_R2s_method_panel = {'sepia_handle_panel_R2s_Trapezoidal',...
                             'sepia_handle_panel_R2s_ARLO',...
                             'sepia_handle_panel_R2s_GeometricSum',...
                             'sepia_handle_panel_R2s_SequenceOfProduct',...
                             'sepia_handle_panel_R2s_LinearRegression',...
                             'sepia_handle_panel_R2s_NLLS',...
                             };
                             % in future, add panel of new method here
                             
%% functions that generate and read BFR algorithm parameters (Optional, for GUI)
% Specify the name of the function that export/import parameters to/from
% output config file
config_R2s_function     = {'get_set_r2s_Trapezoidal',...
                           'get_set_r2s_ARLO',...
                           'get_set_r2s_GeometricSum',...
                           'get_set_r2s_SequenceOfProduct',...
                           'get_set_r2s_LinearRegression',...
                           'get_set_r2s_NLLS',...
                           };
                       % in future, add panel of new method here
