%% sepia_configuration_QSM
%
% Description: a script contains all the QSM method names and related function names
%
% Kwok-shing Chan @ DCCN
% k.chan@donders.ru.nl
% Date created: 11 March 2020
% Date modified: 
%
% DO NOT change the variable name
% DO NOT change the order of the entities, add a new one at the end instead
% The order of the methods MUST be consistent across all variables
%
%% QSM dipole inversion methods available in SEPIA (MUST)
% Specify the names of the methods
methodQSMName           = {'TKD',...
                           'Closed-form solution',...
                           'STI suite iLSQR',...
                           'iLSQR',...
                           'FANSI',...
                           'Star-QSM',...
                           'MEDI'};
                       % in future, add panel of new method here

%% Wrapper to access algorithms (MUST)
% Specify the name of the wrapper function to connect SEPIA and the
% algorithm
wrapper_QSM_function    = {'Wrapper_QSM_TKD',...
                           'Wrapper_QSM_CFSL2',...
                           'Wrapper_QSM_STISuiteiLSQRv3',...
                           'Wrapper_QSM_iLSQR',...
                           'Wrapper_QSM_FANSI',...
                           'Wrapper_QSM_StarQSM',...
                           'Wrapper_QSM_MEDI',...
                           } ;
                       % in future, add panel of new method here

%% function that create the method specific panel (Optional, for GUI)
% Specify the name of the function of the panel design 
function_QSM_method_panel = {'sepia_handle_panel_qsm_TKD',...
                             'sepia_handle_panel_qsm_CFS',...
                             'sepia_handle_panel_qsm_STIiLSQR',...
                             'sepia_handle_panel_qsm_iLSQR',...
                             'sepia_handle_panel_qsm_FANSI',...
                             'sepia_handle_panel_qsm_Star',...
                             'sepia_handle_panel_qsm_MEDI',...
                             };
                             % in future, add panel of new method here
                             
%% functions that generate and read algorithm parameters (Optional, for GUI)
% Specify the name of the function that export/import parameters to/from
% output config file
config_QSM_function     = {'get_set_qsm_tkd',...
                           'get_set_qsm_cfs',...
                           'get_set_qsm_stisuiteilsqr',...
                           'get_set_qsm_ilsqr',...
                           'get_set_qsm_fansi',...
                           'get_set_qsm_starqsm',...
                           'get_set_qsm_medi',...
                           };
                       % in future, add panel of new method here
